/**
 * exampleGraphs.ts — 100+ curated example graphs by domain (12.8).
 *
 * Each entry is a self-contained EngineSnapshotV1-compatible graph that can be
 * opened and run immediately. Examples cover mechanical, electrical, thermal,
 * fluid, control, ML, optimisation, vehicle, and signal processing domains.
 *
 * Usage:
 *   EXAMPLE_GRAPHS            — flat array of all examples
 *   EXAMPLE_GRAPH_CATALOG     — grouped by domain
 *   searchExamples(query)     — fuzzy search by name/tags/description
 *   getExamplesByDomain(d)    — filter by domain
 */

// ── Types ──────────────────────────────────────────────────────────────────────

export type ExampleDomain =
  | 'mechanical'
  | 'electrical'
  | 'thermal'
  | 'fluid'
  | 'control'
  | 'ml'
  | 'optimisation'
  | 'vehicle'
  | 'signal'
  | 'math'
  | 'data'
  | 'finance'

export interface ExampleGraph {
  id: string
  title: string
  domain: ExampleDomain
  description: string
  tags: string[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  /** EngineSnapshotV1-compatible graph data */
  graph: {
    version: 1
    nodes: Array<{ id: string; blockType: string; position?: { x: number; y: number }; data: Record<string, unknown> }>
    edges: Array<{ id: string; source: string; sourceHandle: string; target: string; targetHandle: string }>
  }
}

// ── Helper to build simple graphs ─────────────────────────────────────────────

function n(id: string, blockType: string, data: Record<string, unknown> = {}, x = 0, y = 0) {
  return { id, blockType, position: { x, y }, data: { blockType, ...data } }
}

function e(id: string, src: string, srcH: string, tgt: string, tgtH: string) {
  return { id, source: src, sourceHandle: srcH, target: tgt, targetHandle: tgtH }
}

function g(nodes: ReturnType<typeof n>[], edges: ReturnType<typeof e>[]): ExampleGraph['graph'] {
  return { version: 1, nodes, edges }
}

// ── MECHANICAL ──────────────────────────────────────────────────────────────

const MECHANICAL: ExampleGraph[] = [
  {
    id: 'mech_spring_force',
    title: "Hooke's Law: Spring Force",
    domain: 'mechanical',
    description: "Compute spring force F = k·x. Adjust stiffness k and displacement x.",
    tags: ['spring', 'hooke', 'force', 'beginner'],
    difficulty: 'beginner',
    graph: g([
      n('k', 'number', { label: 'Stiffness k (N/m)', value: 100 }, 0, 0),
      n('x', 'number', { label: 'Displacement x (m)', value: 0.05 }, 0, 80),
      n('mul', 'multiply', { label: 'F = k·x' }, 200, 40),
      n('disp', 'display', { label: 'Force F (N)' }, 400, 40),
    ], [
      e('e1', 'k', 'out', 'mul', 'in_0'),
      e('e2', 'x', 'out', 'mul', 'in_1'),
      e('e3', 'mul', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_kinetic_energy',
    title: 'Kinetic Energy',
    domain: 'mechanical',
    description: 'KE = ½mv². Enter mass and velocity to compute kinetic energy.',
    tags: ['kinetic energy', 'mechanics', 'velocity', 'mass'],
    difficulty: 'beginner',
    graph: g([
      n('m', 'number', { label: 'Mass (kg)', value: 10 }, 0, 0),
      n('v', 'number', { label: 'Velocity (m/s)', value: 5 }, 0, 80),
      n('v2', 'multiply', { label: 'v²' }, 200, 80),
      n('half', 'number', { label: '½', value: 0.5 }, 0, 160),
      n('mul', 'multiply', { label: 'KE = ½mv²' }, 400, 80),
      n('disp', 'display', { label: 'KE (J)' }, 600, 80),
    ], [
      e('e1', 'v', 'out', 'v2', 'in_0'),
      e('e2', 'v', 'out', 'v2', 'in_1'),
      e('e3', 'm', 'out', 'mul', 'in_0'),
      e('e4', 'v2', 'out', 'mul', 'in_1'),
      e('e5', 'mul', 'out', 'mul2', 'in_0'),
    ].concat([e('e6', 'half', 'out', 'mul', 'in_1'), e('e7', 'mul', 'out', 'disp', 'in')])),
  },
  {
    id: 'mech_projectile_range',
    title: 'Projectile Range',
    domain: 'mechanical',
    description: 'Horizontal range R = v₀²sin(2θ)/g. Vary launch angle θ and initial speed.',
    tags: ['projectile', 'range', 'angle', 'gravity'],
    difficulty: 'beginner',
    graph: g([
      n('v0', 'number', { label: 'v₀ (m/s)', value: 20 }, 0, 0),
      n('theta', 'number', { label: 'θ (deg)', value: 45 }, 0, 80),
      n('g', 'constant', { label: 'g', constantId: 'g_std' }, 0, 160),
      n('deg2rad', 'multiply', { label: 'θ rad' }, 160, 80),
      n('pi_180', 'number', { label: 'π/180', value: 0.017453293 }, 0, 240),
      n('two_theta', 'multiply', { label: '2θ' }, 300, 80),
      n('two', 'number', { label: '2', value: 2 }, 160, 0),
      n('sin2t', 'sin', { label: 'sin(2θ)' }, 460, 80),
      n('v0sq', 'multiply', { label: 'v₀²' }, 160, -80),
      n('num', 'multiply', { label: 'v₀²sin(2θ)' }, 600, 0),
      n('range', 'divide', { label: 'R = v₀²sin(2θ)/g' }, 760, 0),
      n('disp', 'display', { label: 'Range R (m)' }, 920, 0),
    ], [
      e('e1', 'theta', 'out', 'deg2rad', 'in_0'),
      e('e2', 'pi_180', 'out', 'deg2rad', 'in_1'),
      e('e3', 'two', 'out', 'two_theta', 'in_0'),
      e('e4', 'deg2rad', 'out', 'two_theta', 'in_1'),
      e('e5', 'two_theta', 'out', 'sin2t', 'in'),
      e('e6', 'v0', 'out', 'v0sq', 'in_0'),
      e('e7', 'v0', 'out', 'v0sq', 'in_1'),
      e('e8', 'v0sq', 'out', 'num', 'in_0'),
      e('e9', 'sin2t', 'out', 'num', 'in_1'),
      e('e10', 'num', 'out', 'range', 'in_0'),
      e('e11', 'g', 'out', 'range', 'in_1'),
      e('e12', 'range', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_stress_strain',
    title: 'Stress and Strain',
    domain: 'mechanical',
    description: 'σ = E·ε: axial stress from Young\'s modulus and strain.',
    tags: ['stress', 'strain', 'young modulus', 'elasticity'],
    difficulty: 'beginner',
    graph: g([
      n('E', 'number', { label: "Young's Modulus E (GPa)", value: 200 }, 0, 0),
      n('eps', 'number', { label: 'Strain ε', value: 0.001 }, 0, 80),
      n('mul', 'multiply', { label: 'σ = E·ε' }, 200, 40),
      n('disp', 'display', { label: 'Stress σ (GPa)' }, 400, 40),
    ], [
      e('e1', 'E', 'out', 'mul', 'in_0'),
      e('e2', 'eps', 'out', 'mul', 'in_1'),
      e('e3', 'mul', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_natural_frequency',
    title: 'Natural Frequency',
    domain: 'mechanical',
    description: 'ωₙ = √(k/m). Spring-mass natural frequency.',
    tags: ['natural frequency', 'spring mass', 'vibration'],
    difficulty: 'beginner',
    graph: g([
      n('k', 'number', { label: 'Stiffness k (N/m)', value: 1000 }, 0, 0),
      n('m', 'number', { label: 'Mass m (kg)', value: 10 }, 0, 80),
      n('div', 'divide', { label: 'k/m' }, 200, 40),
      n('sqr', 'sqrt', { label: 'ωₙ = √(k/m)' }, 380, 40),
      n('disp', 'display', { label: 'ωₙ (rad/s)' }, 540, 40),
    ], [
      e('e1', 'k', 'out', 'div', 'in_0'),
      e('e2', 'm', 'out', 'div', 'in_1'),
      e('e3', 'div', 'out', 'sqr', 'in'),
      e('e4', 'sqr', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_damping_ratio',
    title: 'Damping Ratio',
    domain: 'mechanical',
    description: 'ζ = c/(2√(km)). Compute damping ratio for spring-damper-mass system.',
    tags: ['damping', 'vibration', 'critical damping'],
    difficulty: 'intermediate',
    graph: g([
      n('c', 'number', { label: 'Damping c (Ns/m)', value: 50 }, 0, 0),
      n('k', 'number', { label: 'Stiffness k (N/m)', value: 1000 }, 0, 80),
      n('m', 'number', { label: 'Mass m (kg)', value: 10 }, 0, 160),
      n('km', 'multiply', { label: 'k·m' }, 200, 120),
      n('sqrkm', 'sqrt', { label: '√(km)' }, 370, 120),
      n('two', 'number', { label: '2', value: 2 }, 200, 40),
      n('ccr', 'multiply', { label: '2√(km)' }, 530, 80),
      n('zeta', 'divide', { label: 'ζ = c/ccr' }, 700, 40),
      n('disp', 'display', { label: 'Damping ratio ζ' }, 880, 40),
    ], [
      e('e1', 'k', 'out', 'km', 'in_0'),
      e('e2', 'm', 'out', 'km', 'in_1'),
      e('e3', 'km', 'out', 'sqrkm', 'in'),
      e('e4', 'two', 'out', 'ccr', 'in_0'),
      e('e5', 'sqrkm', 'out', 'ccr', 'in_1'),
      e('e6', 'c', 'out', 'zeta', 'in_0'),
      e('e7', 'ccr', 'out', 'zeta', 'in_1'),
      e('e8', 'zeta', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_beam_deflection',
    title: 'Simply Supported Beam Deflection',
    domain: 'mechanical',
    description: 'Mid-span deflection δ = 5wL⁴/(384EI) for UDL.',
    tags: ['beam', 'deflection', 'bending', 'structural'],
    difficulty: 'intermediate',
    graph: g([
      n('w', 'number', { label: 'UDL w (N/m)', value: 1000 }, 0, 0),
      n('L', 'number', { label: 'Span L (m)', value: 5 }, 0, 80),
      n('E', 'number', { label: "Young's E (GPa)", value: 200e9 }, 0, 160),
      n('I', 'number', { label: 'Second moment I (m⁴)', value: 1e-4 }, 0, 240),
      n('L4', 'pow', { label: 'L⁴', exponent: 4 }, 200, 80),
      n('num5', 'number', { label: '5', value: 5 }, 200, 0),
      n('n384', 'number', { label: '384', value: 384 }, 200, 300),
      n('numer', 'multiply', { label: '5wL⁴' }, 400, 40),
      n('EI', 'multiply', { label: 'EI' }, 400, 200),
      n('denom', 'multiply', { label: '384EI' }, 560, 200),
      n('delta', 'divide', { label: 'δ = 5wL⁴/384EI' }, 720, 120),
      n('disp', 'display', { label: 'Deflection δ (m)' }, 900, 120),
    ], [
      e('e1', 'L', 'out', 'L4', 'in'),
      e('e2', 'num5', 'out', 'numer', 'in_0'),
      e('e3', 'w', 'out', 'numer', 'in_1'),
      e('e4', 'L4', 'out', 'numer', 'in_2'),
      e('e5', 'E', 'out', 'EI', 'in_0'),
      e('e6', 'I', 'out', 'EI', 'in_1'),
      e('e7', 'n384', 'out', 'denom', 'in_0'),
      e('e8', 'EI', 'out', 'denom', 'in_1'),
      e('e9', 'numer', 'out', 'delta', 'in_0'),
      e('e10', 'denom', 'out', 'delta', 'in_1'),
      e('e11', 'delta', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_momentum',
    title: 'Momentum and Impulse',
    domain: 'mechanical',
    description: 'p = mv; impulse J = F·Δt = Δp.',
    tags: ['momentum', 'impulse', 'Newton'],
    difficulty: 'beginner',
    graph: g([
      n('m', 'number', { label: 'Mass (kg)', value: 5 }, 0, 0),
      n('v', 'number', { label: 'Velocity (m/s)', value: 10 }, 0, 80),
      n('mom', 'multiply', { label: 'p = mv' }, 200, 40),
      n('disp', 'display', { label: 'Momentum (kg⋅m/s)' }, 400, 40),
    ], [
      e('e1', 'm', 'out', 'mom', 'in_0'),
      e('e2', 'v', 'out', 'mom', 'in_1'),
      e('e3', 'mom', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_torque_power',
    title: 'Torque and Shaft Power',
    domain: 'mechanical',
    description: 'P = T·ω. Shaft power from torque and angular velocity.',
    tags: ['torque', 'power', 'shaft', 'rotation'],
    difficulty: 'beginner',
    graph: g([
      n('T', 'number', { label: 'Torque T (N⋅m)', value: 200 }, 0, 0),
      n('omega', 'number', { label: 'ω (rad/s)', value: 150 }, 0, 80),
      n('P', 'multiply', { label: 'P = T·ω' }, 200, 40),
      n('disp', 'display', { label: 'Power P (W)' }, 400, 40),
    ], [
      e('e1', 'T', 'out', 'P', 'in_0'),
      e('e2', 'omega', 'out', 'P', 'in_1'),
      e('e3', 'P', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'mech_centripetal',
    title: 'Centripetal Force',
    domain: 'mechanical',
    description: 'F_c = m·v²/r. Centripetal force in circular motion.',
    tags: ['centripetal', 'circular motion', 'rotation'],
    difficulty: 'beginner',
    graph: g([
      n('m', 'number', { label: 'Mass (kg)', value: 2 }, 0, 0),
      n('v', 'number', { label: 'Speed (m/s)', value: 10 }, 0, 80),
      n('r', 'number', { label: 'Radius (m)', value: 5 }, 0, 160),
      n('v2', 'multiply', { label: 'v²' }, 200, 80),
      n('mv2', 'multiply', { label: 'mv²' }, 360, 40),
      n('Fc', 'divide', { label: 'Fc = mv²/r' }, 520, 80),
      n('disp', 'display', { label: 'Centripetal F (N)' }, 700, 80),
    ], [
      e('e1', 'v', 'out', 'v2', 'in_0'),
      e('e2', 'v', 'out', 'v2', 'in_1'),
      e('e3', 'm', 'out', 'mv2', 'in_0'),
      e('e4', 'v2', 'out', 'mv2', 'in_1'),
      e('e5', 'mv2', 'out', 'Fc', 'in_0'),
      e('e6', 'r', 'out', 'Fc', 'in_1'),
      e('e7', 'Fc', 'out', 'disp', 'in'),
    ]),
  },
]

// ── ELECTRICAL ─────────────────────────────────────────────────────────────

const ELECTRICAL: ExampleGraph[] = [
  {
    id: 'elec_ohm',
    title: "Ohm's Law",
    domain: 'electrical',
    description: 'V = IR. Voltage across a resistor.',
    tags: ['ohm', 'voltage', 'current', 'resistance'],
    difficulty: 'beginner',
    graph: g([
      n('I', 'number', { label: 'Current I (A)', value: 2 }, 0, 0),
      n('R', 'number', { label: 'Resistance R (Ω)', value: 100 }, 0, 80),
      n('V', 'multiply', { label: 'V = IR' }, 200, 40),
      n('disp', 'display', { label: 'Voltage V' }, 400, 40),
    ], [
      e('e1', 'I', 'out', 'V', 'in_0'),
      e('e2', 'R', 'out', 'V', 'in_1'),
      e('e3', 'V', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_power',
    title: 'Electrical Power',
    domain: 'electrical',
    description: 'P = V·I = I²R = V²/R. Three forms of electrical power.',
    tags: ['power', 'watts', 'dissipation'],
    difficulty: 'beginner',
    graph: g([
      n('V', 'number', { label: 'Voltage V', value: 12 }, 0, 0),
      n('I', 'number', { label: 'Current I', value: 2 }, 0, 80),
      n('P', 'multiply', { label: 'P = VI' }, 200, 40),
      n('disp', 'display', { label: 'Power P (W)' }, 400, 40),
    ], [
      e('e1', 'V', 'out', 'P', 'in_0'),
      e('e2', 'I', 'out', 'P', 'in_1'),
      e('e3', 'P', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_rc_time',
    title: 'RC Circuit Time Constant',
    domain: 'electrical',
    description: 'τ = RC. Time constant of a series RC circuit.',
    tags: ['RC', 'time constant', 'capacitor', 'filter'],
    difficulty: 'beginner',
    graph: g([
      n('R', 'number', { label: 'R (Ω)', value: 10000 }, 0, 0),
      n('C', 'number', { label: 'C (F)', value: 1e-6 }, 0, 80),
      n('tau', 'multiply', { label: 'τ = RC' }, 200, 40),
      n('disp', 'display', { label: 'τ (s)' }, 400, 40),
    ], [
      e('e1', 'R', 'out', 'tau', 'in_0'),
      e('e2', 'C', 'out', 'tau', 'in_1'),
      e('e3', 'tau', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_rlc_resonance',
    title: 'RLC Resonant Frequency',
    domain: 'electrical',
    description: 'f₀ = 1/(2π√(LC)). Resonant frequency of an LC tank circuit.',
    tags: ['RLC', 'resonance', 'frequency', 'inductor', 'capacitor'],
    difficulty: 'intermediate',
    graph: g([
      n('L', 'number', { label: 'Inductance L (H)', value: 1e-3 }, 0, 0),
      n('C', 'number', { label: 'Capacitance C (F)', value: 1e-9 }, 0, 80),
      n('LC', 'multiply', { label: 'LC' }, 200, 40),
      n('sqrtLC', 'sqrt', { label: '√(LC)' }, 370, 40),
      n('two_pi', 'number', { label: '2π', value: 6.2831853 }, 200, 160),
      n('denom', 'multiply', { label: '2π√(LC)' }, 530, 100),
      n('one', 'number', { label: '1', value: 1 }, 370, 160),
      n('f0', 'divide', { label: 'f₀' }, 700, 100),
      n('disp', 'display', { label: 'f₀ (Hz)' }, 880, 100),
    ], [
      e('e1', 'L', 'out', 'LC', 'in_0'),
      e('e2', 'C', 'out', 'LC', 'in_1'),
      e('e3', 'LC', 'out', 'sqrtLC', 'in'),
      e('e4', 'two_pi', 'out', 'denom', 'in_0'),
      e('e5', 'sqrtLC', 'out', 'denom', 'in_1'),
      e('e6', 'one', 'out', 'f0', 'in_0'),
      e('e7', 'denom', 'out', 'f0', 'in_1'),
      e('e8', 'f0', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_parallel_resistance',
    title: 'Parallel Resistors',
    domain: 'electrical',
    description: '1/R_total = 1/R1 + 1/R2. Two parallel resistors.',
    tags: ['resistors', 'parallel', 'combination'],
    difficulty: 'beginner',
    graph: g([
      n('R1', 'number', { label: 'R1 (Ω)', value: 100 }, 0, 0),
      n('R2', 'number', { label: 'R2 (Ω)', value: 200 }, 0, 80),
      n('one', 'number', { label: '1', value: 1 }, 0, 240),
      n('inv1', 'divide', { label: '1/R1' }, 200, 0),
      n('inv2', 'divide', { label: '1/R2' }, 200, 80),
      n('sum_inv', 'add', { label: '1/R1 + 1/R2' }, 400, 40),
      n('Rtot', 'divide', { label: 'R_total' }, 600, 40),
      n('disp', 'display', { label: 'R_total (Ω)' }, 800, 40),
    ], [
      e('e1', 'one', 'out', 'inv1', 'in_0'),
      e('e2', 'R1', 'out', 'inv1', 'in_1'),
      e('e3', 'one', 'out', 'inv2', 'in_0'),
      e('e4', 'R2', 'out', 'inv2', 'in_1'),
      e('e5', 'inv1', 'out', 'sum_inv', 'in_0'),
      e('e6', 'inv2', 'out', 'sum_inv', 'in_1'),
      e('e7', 'one', 'out', 'Rtot', 'in_0'),
      e('e8', 'sum_inv', 'out', 'Rtot', 'in_1'),
      e('e9', 'Rtot', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_capacitor_energy',
    title: 'Capacitor Stored Energy',
    domain: 'electrical',
    description: 'E = ½CV². Energy stored in a charged capacitor.',
    tags: ['capacitor', 'energy', 'storage'],
    difficulty: 'beginner',
    graph: g([
      n('C', 'number', { label: 'Capacitance C (F)', value: 100e-6 }, 0, 0),
      n('V', 'number', { label: 'Voltage V', value: 24 }, 0, 80),
      n('V2', 'multiply', { label: 'V²' }, 200, 80),
      n('CV2', 'multiply', { label: 'CV²' }, 380, 40),
      n('half', 'number', { label: '0.5', value: 0.5 }, 200, 0),
      n('E', 'multiply', { label: 'E = ½CV²' }, 560, 40),
      n('disp', 'display', { label: 'Energy E (J)' }, 740, 40),
    ], [
      e('e1', 'V', 'out', 'V2', 'in_0'),
      e('e2', 'V', 'out', 'V2', 'in_1'),
      e('e3', 'C', 'out', 'CV2', 'in_0'),
      e('e4', 'V2', 'out', 'CV2', 'in_1'),
      e('e5', 'half', 'out', 'E', 'in_0'),
      e('e6', 'CV2', 'out', 'E', 'in_1'),
      e('e7', 'E', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'elec_impedance_rc',
    title: 'RC Impedance at Frequency',
    domain: 'electrical',
    description: '|Z| = √(R² + (1/ωC)²). Magnitude of RC series impedance.',
    tags: ['impedance', 'RC', 'frequency', 'AC'],
    difficulty: 'intermediate',
    graph: g([
      n('R', 'number', { label: 'R (Ω)', value: 1000 }, 0, 0),
      n('f', 'number', { label: 'Frequency f (Hz)', value: 1000 }, 0, 80),
      n('C', 'number', { label: 'C (F)', value: 1e-6 }, 0, 160),
      n('twopi', 'number', { label: '2π', value: 6.2831853 }, 200, 80),
      n('omega', 'multiply', { label: 'ω = 2πf' }, 360, 80),
      n('omegaC', 'multiply', { label: 'ωC' }, 520, 80),
      n('one', 'number', { label: '1', value: 1 }, 360, 160),
      n('Xc', 'divide', { label: 'Xc = 1/ωC' }, 680, 120),
      n('R2', 'multiply', { label: 'R²' }, 200, -40),
      n('Xc2', 'multiply', { label: 'Xc²' }, 840, 120),
      n('sum', 'add', { label: 'R²+Xc²' }, 1000, 40),
      n('Z', 'sqrt', { label: '|Z|' }, 1160, 40),
      n('disp', 'display', { label: '|Z| (Ω)' }, 1320, 40),
    ], [
      e('e1', 'twopi', 'out', 'omega', 'in_0'),
      e('e2', 'f', 'out', 'omega', 'in_1'),
      e('e3', 'omega', 'out', 'omegaC', 'in_0'),
      e('e4', 'C', 'out', 'omegaC', 'in_1'),
      e('e5', 'one', 'out', 'Xc', 'in_0'),
      e('e6', 'omegaC', 'out', 'Xc', 'in_1'),
      e('e7', 'R', 'out', 'R2', 'in_0'),
      e('e8', 'R', 'out', 'R2', 'in_1'),
      e('e9', 'Xc', 'out', 'Xc2', 'in_0'),
      e('e10', 'Xc', 'out', 'Xc2', 'in_1'),
      e('e11', 'R2', 'out', 'sum', 'in_0'),
      e('e12', 'Xc2', 'out', 'sum', 'in_1'),
      e('e13', 'sum', 'out', 'Z', 'in'),
      e('e14', 'Z', 'out', 'disp', 'in'),
    ]),
  },
]

// ── THERMAL ─────────────────────────────────────────────────────────────────

const THERMAL: ExampleGraph[] = [
  {
    id: 'therm_newtons_cooling',
    title: "Newton's Law of Cooling",
    domain: 'thermal',
    description: 'dT/dt = -k(T - T∞). Rate of temperature change.',
    tags: ['cooling', 'Newton', 'heat transfer'],
    difficulty: 'beginner',
    graph: g([
      n('T', 'number', { label: 'Temperature T (°C)', value: 80 }, 0, 0),
      n('Tinf', 'number', { label: 'Ambient T∞ (°C)', value: 20 }, 0, 80),
      n('k', 'number', { label: 'Cooling const k (1/s)', value: 0.05 }, 0, 160),
      n('diff', 'subtract', { label: 'T - T∞' }, 200, 40),
      n('rate', 'multiply', { label: 'k(T - T∞)' }, 380, 80),
      n('neg', 'negate', { label: 'dT/dt' }, 560, 80),
      n('disp', 'display', { label: 'dT/dt (°C/s)' }, 740, 80),
    ], [
      e('e1', 'T', 'out', 'diff', 'in_0'),
      e('e2', 'Tinf', 'out', 'diff', 'in_1'),
      e('e3', 'k', 'out', 'rate', 'in_0'),
      e('e4', 'diff', 'out', 'rate', 'in_1'),
      e('e5', 'rate', 'out', 'neg', 'in'),
      e('e6', 'neg', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'therm_fourier',
    title: "Fourier's Law of Conduction",
    domain: 'thermal',
    description: 'q = -kA(ΔT/Δx). Heat flux through a wall.',
    tags: ['conduction', 'Fourier', 'heat flux', 'wall'],
    difficulty: 'beginner',
    graph: g([
      n('k', 'number', { label: 'Conductivity k (W/mK)', value: 50 }, 0, 0),
      n('A', 'number', { label: 'Area A (m²)', value: 1 }, 0, 80),
      n('dT', 'number', { label: 'ΔT (K)', value: 100 }, 0, 160),
      n('dx', 'number', { label: 'Thickness Δx (m)', value: 0.1 }, 0, 240),
      n('grad', 'divide', { label: 'ΔT/Δx' }, 200, 200),
      n('kA', 'multiply', { label: 'kA' }, 200, 40),
      n('q_abs', 'multiply', { label: 'kA·ΔT/Δx' }, 400, 120),
      n('disp', 'display', { label: 'Heat flux q (W)' }, 600, 120),
    ], [
      e('e1', 'k', 'out', 'kA', 'in_0'),
      e('e2', 'A', 'out', 'kA', 'in_1'),
      e('e3', 'dT', 'out', 'grad', 'in_0'),
      e('e4', 'dx', 'out', 'grad', 'in_1'),
      e('e5', 'kA', 'out', 'q_abs', 'in_0'),
      e('e6', 'grad', 'out', 'q_abs', 'in_1'),
      e('e7', 'q_abs', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'therm_stefan_boltzmann',
    title: 'Stefan-Boltzmann Radiation',
    domain: 'thermal',
    description: 'q = εσT⁴. Radiative heat emission from a surface.',
    tags: ['radiation', 'Stefan-Boltzmann', 'emissivity', 'blackbody'],
    difficulty: 'intermediate',
    graph: g([
      n('eps', 'number', { label: 'Emissivity ε', value: 0.9 }, 0, 0),
      n('sigma', 'constant', { label: 'σ (Stefan-Boltzmann)', constantId: 'stefan_boltzmann' }, 0, 80),
      n('T', 'number', { label: 'Temperature T (K)', value: 600 }, 0, 160),
      n('T4', 'pow', { label: 'T⁴', exponent: 4 }, 200, 160),
      n('eps_sigma', 'multiply', { label: 'εσ' }, 200, 40),
      n('q', 'multiply', { label: 'q = εσT⁴' }, 400, 100),
      n('disp', 'display', { label: 'q (W/m²)' }, 600, 100),
    ], [
      e('e1', 'T', 'out', 'T4', 'in'),
      e('e2', 'eps', 'out', 'eps_sigma', 'in_0'),
      e('e3', 'sigma', 'out', 'eps_sigma', 'in_1'),
      e('e4', 'eps_sigma', 'out', 'q', 'in_0'),
      e('e5', 'T4', 'out', 'q', 'in_1'),
      e('e6', 'q', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'therm_thermal_resistance',
    title: 'Thermal Resistance Network',
    domain: 'thermal',
    description: 'R_total = R1 + R2 + R3 (series). Heat flow through composite wall.',
    tags: ['thermal resistance', 'wall', 'composite', 'R-value'],
    difficulty: 'intermediate',
    graph: g([
      n('R1', 'number', { label: 'R₁ (K/W)', value: 0.5 }, 0, 0),
      n('R2', 'number', { label: 'R₂ (K/W)', value: 1.2 }, 0, 80),
      n('R3', 'number', { label: 'R₃ (K/W)', value: 0.3 }, 0, 160),
      n('dT', 'number', { label: 'ΔT (K)', value: 30 }, 0, 240),
      n('Rtot', 'add', { label: 'R_total' }, 200, 80),
      n('q', 'divide', { label: 'q = ΔT/R_total' }, 400, 160),
      n('disp', 'display', { label: 'q (W)' }, 600, 160),
    ], [
      e('e1', 'R1', 'out', 'Rtot', 'in_0'),
      e('e2', 'R2', 'out', 'Rtot', 'in_1'),
      e('e3', 'R3', 'out', 'Rtot', 'in_2'),
      e('e4', 'dT', 'out', 'q', 'in_0'),
      e('e5', 'Rtot', 'out', 'q', 'in_1'),
      e('e6', 'q', 'out', 'disp', 'in'),
    ]),
  },
]

// ── CONTROL ─────────────────────────────────────────────────────────────────

const CONTROL: ExampleGraph[] = [
  {
    id: 'ctrl_pid_output',
    title: 'PID Controller Output',
    domain: 'control',
    description: 'u = Kp·e + Ki·∫e + Kd·de/dt (discretised). Tune PID gains.',
    tags: ['PID', 'control', 'feedback', 'Kp', 'Ki', 'Kd'],
    difficulty: 'intermediate',
    graph: g([
      n('e', 'number', { label: 'Error e', value: 0.5 }, 0, 0),
      n('Kp', 'number', { label: 'Kp', value: 1.0 }, 0, 80),
      n('Ki', 'number', { label: 'Ki', value: 0.5 }, 0, 160),
      n('Kd', 'number', { label: 'Kd', value: 0.1 }, 0, 240),
      n('integral', 'number', { label: '∫e (approx)', value: 0.2 }, 0, 320),
      n('deriv', 'number', { label: 'de/dt (approx)', value: 0.05 }, 0, 400),
      n('P', 'multiply', { label: 'P = Kp·e' }, 200, 40),
      n('I', 'multiply', { label: 'I = Ki·∫e' }, 200, 200),
      n('D', 'multiply', { label: 'D = Kd·de/dt' }, 200, 320),
      n('u', 'add', { label: 'u = P + I + D' }, 400, 200),
      n('disp', 'display', { label: 'Control output u' }, 600, 200),
    ], [
      e('e1', 'Kp', 'out', 'P', 'in_0'),
      e('e2', 'e', 'out', 'P', 'in_1'),
      e('e3', 'Ki', 'out', 'I', 'in_0'),
      e('e4', 'integral', 'out', 'I', 'in_1'),
      e('e5', 'Kd', 'out', 'D', 'in_0'),
      e('e6', 'deriv', 'out', 'D', 'in_1'),
      e('e7', 'P', 'out', 'u', 'in_0'),
      e('e8', 'I', 'out', 'u', 'in_1'),
      e('e9', 'D', 'out', 'u', 'in_2'),
      e('e10', 'u', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'ctrl_first_order_response',
    title: 'First-Order Step Response',
    domain: 'control',
    description: 'G(s) = K/(τs+1). Time constant and steady-state gain.',
    tags: ['transfer function', 'step response', 'first order', 'time constant'],
    difficulty: 'intermediate',
    graph: g([
      n('K', 'number', { label: 'DC gain K', value: 2 }, 0, 0),
      n('tau', 'number', { label: 'Time constant τ (s)', value: 1 }, 0, 80),
      n('t', 'number', { label: 'Time t (s)', value: 2 }, 0, 160),
      n('t_tau', 'divide', { label: 't/τ' }, 200, 120),
      n('neg_t_tau', 'negate', { label: '-t/τ' }, 360, 120),
      n('exp_term', 'exp', { label: 'e^(-t/τ)' }, 520, 120),
      n('one', 'number', { label: '1', value: 1 }, 360, 40),
      n('one_minus', 'subtract', { label: '1-e^(-t/τ)' }, 680, 80),
      n('y', 'multiply', { label: 'y(t) = K(1-e^(-t/τ))' }, 840, 40),
      n('disp', 'display', { label: 'y(t)' }, 1020, 40),
    ], [
      e('e1', 't', 'out', 't_tau', 'in_0'),
      e('e2', 'tau', 'out', 't_tau', 'in_1'),
      e('e3', 't_tau', 'out', 'neg_t_tau', 'in'),
      e('e4', 'neg_t_tau', 'out', 'exp_term', 'in'),
      e('e5', 'one', 'out', 'one_minus', 'in_0'),
      e('e6', 'exp_term', 'out', 'one_minus', 'in_1'),
      e('e7', 'K', 'out', 'y', 'in_0'),
      e('e8', 'one_minus', 'out', 'y', 'in_1'),
      e('e9', 'y', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'ctrl_dead_band',
    title: 'Dead-band Zone',
    domain: 'control',
    description: 'Dead-zone non-linearity: output is 0 in band [-dz, +dz].',
    tags: ['dead zone', 'nonlinearity', 'actuator'],
    difficulty: 'intermediate',
    graph: g([
      n('in', 'number', { label: 'Input signal', value: 0.3 }, 0, 0),
      n('dz', 'ctrl.deadZone', { label: 'Dead Zone', deadZone: 0.2 }, 200, 0),
      n('disp', 'display', { label: 'Output' }, 420, 0),
    ], [
      e('e1', 'in', 'out', 'dz', 'in'),
      e('e2', 'dz', 'out', 'disp', 'in'),
    ]),
  },
]

// ── ML ──────────────────────────────────────────────────────────────────────

const ML: ExampleGraph[] = [
  {
    id: 'ml_linear_regression_pred',
    title: 'Linear Regression Prediction',
    domain: 'ml',
    description: 'ŷ = β₀ + β₁x. Simple linear regression prediction.',
    tags: ['linear regression', 'prediction', 'supervised'],
    difficulty: 'beginner',
    graph: g([
      n('x', 'number', { label: 'Feature x', value: 5 }, 0, 0),
      n('b0', 'number', { label: 'Intercept β₀', value: 2.5 }, 0, 80),
      n('b1', 'number', { label: 'Slope β₁', value: 1.3 }, 0, 160),
      n('b1x', 'multiply', { label: 'β₁x' }, 200, 80),
      n('y_hat', 'add', { label: 'ŷ = β₀ + β₁x' }, 400, 80),
      n('disp', 'display', { label: 'Prediction ŷ' }, 600, 80),
    ], [
      e('e1', 'b1', 'out', 'b1x', 'in_0'),
      e('e2', 'x', 'out', 'b1x', 'in_1'),
      e('e3', 'b0', 'out', 'y_hat', 'in_0'),
      e('e4', 'b1x', 'out', 'y_hat', 'in_1'),
      e('e5', 'y_hat', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'ml_sigmoid',
    title: 'Sigmoid Activation',
    domain: 'ml',
    description: 'σ(x) = 1/(1+e^(-x)). Logistic sigmoid function.',
    tags: ['sigmoid', 'activation', 'neural network', 'logistic'],
    difficulty: 'beginner',
    graph: g([
      n('x', 'number', { label: 'Input x', value: 1.5 }, 0, 0),
      n('neg_x', 'negate', { label: '-x' }, 200, 0),
      n('exp_neg', 'exp', { label: 'e^(-x)' }, 360, 0),
      n('one', 'number', { label: '1', value: 1 }, 200, 80),
      n('denom', 'add', { label: '1+e^(-x)' }, 520, 40),
      n('sig', 'divide', { label: 'σ(x) = 1/(1+e^(-x))' }, 680, 40),
      n('disp', 'display', { label: 'σ(x)' }, 860, 40),
    ], [
      e('e1', 'x', 'out', 'neg_x', 'in'),
      e('e2', 'neg_x', 'out', 'exp_neg', 'in'),
      e('e3', 'one', 'out', 'denom', 'in_0'),
      e('e4', 'exp_neg', 'out', 'denom', 'in_1'),
      e('e5', 'one', 'out', 'sig', 'in_0'),
      e('e6', 'denom', 'out', 'sig', 'in_1'),
      e('e7', 'sig', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'ml_mse_loss',
    title: 'MSE Loss',
    domain: 'ml',
    description: 'MSE = (1/n)Σ(ŷ - y)². Mean squared error for two predictions.',
    tags: ['MSE', 'loss', 'supervised', 'regression'],
    difficulty: 'beginner',
    graph: g([
      n('y1', 'number', { label: 'Actual y₁', value: 3.0 }, 0, 0),
      n('y1h', 'number', { label: 'Predicted ŷ₁', value: 2.5 }, 0, 80),
      n('y2', 'number', { label: 'Actual y₂', value: 4.0 }, 0, 160),
      n('y2h', 'number', { label: 'Predicted ŷ₂', value: 4.2 }, 0, 240),
      n('e1b', 'subtract', { label: 'e₁' }, 200, 40),
      n('e2b', 'subtract', { label: 'e₂' }, 200, 200),
      n('e1sq', 'multiply', { label: 'e₁²' }, 380, 40),
      n('e2sq', 'multiply', { label: 'e₂²' }, 380, 200),
      n('sum', 'add', { label: 'Σe²' }, 560, 120),
      n('half', 'number', { label: '0.5', value: 0.5 }, 560, 40),
      n('mse', 'multiply', { label: 'MSE' }, 740, 80),
      n('disp', 'display', { label: 'MSE' }, 920, 80),
    ], [
      e('e1', 'y1h', 'out', 'e1b', 'in_0'),
      e('e2', 'y1', 'out', 'e1b', 'in_1'),
      e('e3', 'y2h', 'out', 'e2b', 'in_0'),
      e('e4', 'y2', 'out', 'e2b', 'in_1'),
      e('e5', 'e1b', 'out', 'e1sq', 'in_0'),
      e('e6', 'e1b', 'out', 'e1sq', 'in_1'),
      e('e7', 'e2b', 'out', 'e2sq', 'in_0'),
      e('e8', 'e2b', 'out', 'e2sq', 'in_1'),
      e('e9', 'e1sq', 'out', 'sum', 'in_0'),
      e('e10', 'e2sq', 'out', 'sum', 'in_1'),
      e('e11', 'half', 'out', 'mse', 'in_0'),
      e('e12', 'sum', 'out', 'mse', 'in_1'),
      e('e13', 'mse', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'ml_softmax_binary',
    title: 'Softmax (2 classes)',
    domain: 'ml',
    description: 'Softmax probabilities for 2 logits: p_i = e^z_i / Σe^z_j.',
    tags: ['softmax', 'classification', 'probability', 'neural network'],
    difficulty: 'intermediate',
    graph: g([
      n('z1', 'number', { label: 'Logit z₁', value: 2.0 }, 0, 0),
      n('z2', 'number', { label: 'Logit z₂', value: 0.5 }, 0, 80),
      n('e1', 'exp', { label: 'e^z₁' }, 200, 0),
      n('e2', 'exp', { label: 'e^z₂' }, 200, 80),
      n('sumE', 'add', { label: 'Σe^z' }, 380, 40),
      n('p1', 'divide', { label: 'p₁' }, 560, 0),
      n('p2', 'divide', { label: 'p₂' }, 560, 80),
      n('disp1', 'display', { label: 'P(class 1)' }, 740, 0),
      n('disp2', 'display', { label: 'P(class 2)' }, 740, 80),
    ], [
      e('e1', 'z1', 'out', 'e1', 'in'),
      e('e2', 'z2', 'out', 'e2', 'in'),
      e('e3', 'e1', 'out', 'sumE', 'in_0'),
      e('e4', 'e2', 'out', 'sumE', 'in_1'),
      e('e5', 'e1', 'out', 'p1', 'in_0'),
      e('e6', 'sumE', 'out', 'p1', 'in_1'),
      e('e7', 'e2', 'out', 'p2', 'in_0'),
      e('e8', 'sumE', 'out', 'p2', 'in_1'),
      e('e9', 'p1', 'out', 'disp1', 'in'),
      e('e10', 'p2', 'out', 'disp2', 'in'),
    ]),
  },
]

// ── OPTIMISATION ────────────────────────────────────────────────────────────

const OPTIMISATION: ExampleGraph[] = [
  {
    id: 'optim_rosenbrock',
    title: 'Rosenbrock Function',
    domain: 'optimisation',
    description: 'f(x,y) = (1-x)² + 100(y-x²)². Classic optimisation test function (minimum at (1,1)).',
    tags: ['Rosenbrock', 'benchmark', 'banana function', 'non-convex'],
    difficulty: 'intermediate',
    graph: g([
      n('x', 'slider', { label: 'x', value: 0, min: -2, max: 2, step: 0.01 }, 0, 0),
      n('y', 'slider', { label: 'y', value: 0, min: -2, max: 2, step: 0.01 }, 0, 80),
      n('one_x', 'subtract', { label: '1-x' }, 200, 0),
      n('t1', 'multiply', { label: '(1-x)²' }, 380, 0),
      n('x2', 'multiply', { label: 'x²' }, 200, 160),
      n('y_x2', 'subtract', { label: 'y-x²' }, 380, 120),
      n('t2', 'multiply', { label: '(y-x²)²' }, 560, 120),
      n('hundred', 'number', { label: '100', value: 100 }, 560, 40),
      n('t2_100', 'multiply', { label: '100(y-x²)²' }, 720, 80),
      n('one', 'number', { label: '1', value: 1 }, 200, -80),
      n('f', 'add', { label: 'f(x,y)' }, 900, 40),
      n('disp', 'display', { label: 'Rosenbrock f(x,y)' }, 1080, 40),
    ], [
      e('e1', 'one', 'out', 'one_x', 'in_0'),
      e('e2', 'x', 'out', 'one_x', 'in_1'),
      e('e3', 'one_x', 'out', 't1', 'in_0'),
      e('e4', 'one_x', 'out', 't1', 'in_1'),
      e('e5', 'x', 'out', 'x2', 'in_0'),
      e('e6', 'x', 'out', 'x2', 'in_1'),
      e('e7', 'y', 'out', 'y_x2', 'in_0'),
      e('e8', 'x2', 'out', 'y_x2', 'in_1'),
      e('e9', 'y_x2', 'out', 't2', 'in_0'),
      e('e10', 'y_x2', 'out', 't2', 'in_1'),
      e('e11', 'hundred', 'out', 't2_100', 'in_0'),
      e('e12', 't2', 'out', 't2_100', 'in_1'),
      e('e13', 't1', 'out', 'f', 'in_0'),
      e('e14', 't2_100', 'out', 'f', 'in_1'),
      e('e15', 'f', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'optim_golden_section',
    title: 'Golden Ratio',
    domain: 'optimisation',
    description: 'φ = (1+√5)/2 ≈ 1.618. Golden ratio constant.',
    tags: ['golden ratio', 'Fibonacci', 'constant'],
    difficulty: 'beginner',
    graph: g([
      n('five', 'number', { label: '5', value: 5 }, 0, 0),
      n('sqrt5', 'sqrt', { label: '√5' }, 200, 0),
      n('one', 'number', { label: '1', value: 1 }, 0, 80),
      n('sum', 'add', { label: '1+√5' }, 380, 40),
      n('two', 'number', { label: '2', value: 2 }, 380, 120),
      n('phi', 'divide', { label: 'φ = (1+√5)/2' }, 560, 80),
      n('disp', 'display', { label: 'φ (Golden ratio)' }, 740, 80),
    ], [
      e('e1', 'five', 'out', 'sqrt5', 'in'),
      e('e2', 'one', 'out', 'sum', 'in_0'),
      e('e3', 'sqrt5', 'out', 'sum', 'in_1'),
      e('e4', 'sum', 'out', 'phi', 'in_0'),
      e('e5', 'two', 'out', 'phi', 'in_1'),
      e('e6', 'phi', 'out', 'disp', 'in'),
    ]),
  },
]

// ── VEHICLE ─────────────────────────────────────────────────────────────────

const VEHICLE: ExampleGraph[] = [
  {
    id: 'veh_stopping_distance',
    title: 'Braking Stopping Distance',
    domain: 'vehicle',
    description: 'd = v²/(2μg). Minimum stopping distance with tire friction μ.',
    tags: ['braking', 'stopping distance', 'friction', 'ADAS'],
    difficulty: 'beginner',
    graph: g([
      n('v', 'number', { label: 'Speed v (m/s)', value: 30 }, 0, 0),
      n('mu', 'number', { label: 'Friction coeff μ', value: 0.8 }, 0, 80),
      n('g', 'constant', { label: 'g', constantId: 'g_std' }, 0, 160),
      n('v2', 'multiply', { label: 'v²' }, 200, 0),
      n('mug', 'multiply', { label: 'μg' }, 200, 120),
      n('two', 'number', { label: '2', value: 2 }, 200, 200),
      n('denom', 'multiply', { label: '2μg' }, 380, 160),
      n('d', 'divide', { label: 'd = v²/(2μg)' }, 560, 80),
      n('disp', 'display', { label: 'Stopping dist (m)' }, 740, 80),
    ], [
      e('e1', 'v', 'out', 'v2', 'in_0'),
      e('e2', 'v', 'out', 'v2', 'in_1'),
      e('e3', 'mu', 'out', 'mug', 'in_0'),
      e('e4', 'g', 'out', 'mug', 'in_1'),
      e('e5', 'two', 'out', 'denom', 'in_0'),
      e('e6', 'mug', 'out', 'denom', 'in_1'),
      e('e7', 'v2', 'out', 'd', 'in_0'),
      e('e8', 'denom', 'out', 'd', 'in_1'),
      e('e9', 'd', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'veh_aero_drag',
    title: 'Aerodynamic Drag Force',
    domain: 'vehicle',
    description: 'F_D = ½ρCdAv². Drag force at speed v.',
    tags: ['aerodynamics', 'drag', 'vehicle', 'Cd'],
    difficulty: 'beginner',
    graph: g([
      n('rho', 'number', { label: 'Air density ρ (kg/m³)', value: 1.225 }, 0, 0),
      n('Cd', 'number', { label: 'Drag coefficient Cd', value: 0.3 }, 0, 80),
      n('A', 'number', { label: 'Frontal area A (m²)', value: 2.2 }, 0, 160),
      n('v', 'number', { label: 'Speed v (m/s)', value: 30 }, 0, 240),
      n('v2', 'multiply', { label: 'v²' }, 200, 240),
      n('CdA', 'multiply', { label: 'CdA' }, 200, 80),
      n('half', 'number', { label: '0.5', value: 0.5 }, 200, -80),
      n('rho_half', 'multiply', { label: '½ρ' }, 380, -40),
      n('rho_Cd_A', 'multiply', { label: '½ρCdA' }, 560, 40),
      n('FD', 'multiply', { label: 'F_D = ½ρCdAv²' }, 740, 140),
      n('disp', 'display', { label: 'Drag F_D (N)' }, 920, 140),
    ], [
      e('e1', 'v', 'out', 'v2', 'in_0'),
      e('e2', 'v', 'out', 'v2', 'in_1'),
      e('e3', 'Cd', 'out', 'CdA', 'in_0'),
      e('e4', 'A', 'out', 'CdA', 'in_1'),
      e('e5', 'half', 'out', 'rho_half', 'in_0'),
      e('e6', 'rho', 'out', 'rho_half', 'in_1'),
      e('e7', 'rho_half', 'out', 'rho_Cd_A', 'in_0'),
      e('e8', 'CdA', 'out', 'rho_Cd_A', 'in_1'),
      e('e9', 'rho_Cd_A', 'out', 'FD', 'in_0'),
      e('e10', 'v2', 'out', 'FD', 'in_1'),
      e('e11', 'FD', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'veh_tire_slip_ratio',
    title: 'Tire Slip Ratio',
    domain: 'vehicle',
    description: 'λ = (ωr - v)/v (braking). Longitudinal tire slip ratio.',
    tags: ['tire', 'slip ratio', 'Pacejka', 'traction control'],
    difficulty: 'intermediate',
    graph: g([
      n('omega', 'number', { label: 'Wheel speed ω (rad/s)', value: 40 }, 0, 0),
      n('r', 'number', { label: 'Tire radius r (m)', value: 0.32 }, 0, 80),
      n('v', 'number', { label: 'Vehicle speed v (m/s)', value: 15 }, 0, 160),
      n('omr', 'multiply', { label: 'ωr (wheel surface speed)' }, 200, 40),
      n('diff', 'subtract', { label: 'ωr - v' }, 380, 100),
      n('slip', 'divide', { label: 'λ = (ωr-v)/v' }, 560, 130),
      n('disp', 'display', { label: 'Slip ratio λ' }, 740, 130),
    ], [
      e('e1', 'omega', 'out', 'omr', 'in_0'),
      e('e2', 'r', 'out', 'omr', 'in_1'),
      e('e3', 'omr', 'out', 'diff', 'in_0'),
      e('e4', 'v', 'out', 'diff', 'in_1'),
      e('e5', 'diff', 'out', 'slip', 'in_0'),
      e('e6', 'v', 'out', 'slip', 'in_1'),
      e('e7', 'slip', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'veh_fuel_consumption',
    title: 'Fuel Consumption Rate',
    domain: 'vehicle',
    description: 'ṁ_f = P/(η·LHV). Fuel mass flow from engine power and efficiency.',
    tags: ['fuel consumption', 'engine efficiency', 'LHV', 'thermodynamics'],
    difficulty: 'intermediate',
    graph: g([
      n('P', 'number', { label: 'Engine power P (kW)', value: 50 }, 0, 0),
      n('eta', 'number', { label: 'Thermal efficiency η', value: 0.35 }, 0, 80),
      n('LHV', 'number', { label: 'LHV (MJ/kg)', value: 43.4 }, 0, 160),
      n('eta_LHV', 'multiply', { label: 'η·LHV' }, 200, 120),
      n('mdot', 'divide', { label: 'ṁ_f = P/(η·LHV)' }, 400, 80),
      n('disp', 'display', { label: 'Fuel flow ṁ (kg/s)' }, 600, 80),
    ], [
      e('e1', 'eta', 'out', 'eta_LHV', 'in_0'),
      e('e2', 'LHV', 'out', 'eta_LHV', 'in_1'),
      e('e3', 'P', 'out', 'mdot', 'in_0'),
      e('e4', 'eta_LHV', 'out', 'mdot', 'in_1'),
      e('e5', 'mdot', 'out', 'disp', 'in'),
    ]),
  },
]

// ── SIGNAL ──────────────────────────────────────────────────────────────────

const SIGNAL: ExampleGraph[] = [
  {
    id: 'sig_sin_wave',
    title: 'Sine Wave',
    domain: 'signal',
    description: 'y = A·sin(2πft + φ). Amplitude, frequency and phase.',
    tags: ['sine', 'waveform', 'frequency', 'amplitude'],
    difficulty: 'beginner',
    graph: g([
      n('A', 'number', { label: 'Amplitude A', value: 1 }, 0, 0),
      n('f', 'number', { label: 'Frequency f (Hz)', value: 1 }, 0, 80),
      n('t', 'number', { label: 'Time t (s)', value: 0.25 }, 0, 160),
      n('phi', 'number', { label: 'Phase φ (rad)', value: 0 }, 0, 240),
      n('twopi', 'number', { label: '2π', value: 6.2831853 }, 200, 80),
      n('twopif', 'multiply', { label: '2πf' }, 360, 80),
      n('twopift', 'multiply', { label: '2πft' }, 520, 80),
      n('arg', 'add', { label: '2πft + φ' }, 680, 120),
      n('sinv', 'sin', { label: 'sin(...)' }, 840, 120),
      n('y', 'multiply', { label: 'A·sin(...)' }, 1000, 60),
      n('disp', 'display', { label: 'y(t)' }, 1180, 60),
    ], [
      e('e1', 'twopi', 'out', 'twopif', 'in_0'),
      e('e2', 'f', 'out', 'twopif', 'in_1'),
      e('e3', 'twopif', 'out', 'twopift', 'in_0'),
      e('e4', 't', 'out', 'twopift', 'in_1'),
      e('e5', 'twopift', 'out', 'arg', 'in_0'),
      e('e6', 'phi', 'out', 'arg', 'in_1'),
      e('e7', 'arg', 'out', 'sinv', 'in'),
      e('e8', 'A', 'out', 'y', 'in_0'),
      e('e9', 'sinv', 'out', 'y', 'in_1'),
      e('e10', 'y', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'sig_rms',
    title: 'RMS Value',
    domain: 'signal',
    description: 'V_rms = A/√2. RMS of a sinusoidal signal.',
    tags: ['RMS', 'root mean square', 'AC', 'signal'],
    difficulty: 'beginner',
    graph: g([
      n('A', 'number', { label: 'Peak amplitude A', value: 10 }, 0, 0),
      n('sqrt2', 'number', { label: '√2', value: 1.41421356 }, 0, 80),
      n('Vrms', 'divide', { label: 'V_rms = A/√2' }, 200, 40),
      n('disp', 'display', { label: 'V_rms' }, 400, 40),
    ], [
      e('e1', 'A', 'out', 'Vrms', 'in_0'),
      e('e2', 'sqrt2', 'out', 'Vrms', 'in_1'),
      e('e3', 'Vrms', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'sig_db',
    title: 'Decibel Conversion',
    domain: 'signal',
    description: 'dB = 20·log₁₀(V/V_ref). Convert voltage ratio to decibels.',
    tags: ['decibel', 'dB', 'logarithm', 'audio'],
    difficulty: 'beginner',
    graph: g([
      n('V', 'number', { label: 'Signal V', value: 2.0 }, 0, 0),
      n('Vref', 'number', { label: 'Reference V_ref', value: 1.0 }, 0, 80),
      n('ratio', 'divide', { label: 'V/V_ref' }, 200, 40),
      n('log10v', 'log10', { label: 'log₁₀(V/V_ref)' }, 380, 40),
      n('twenty', 'number', { label: '20', value: 20 }, 380, 120),
      n('dB', 'multiply', { label: 'dB = 20·log₁₀(...)' }, 560, 80),
      n('disp', 'display', { label: 'dB' }, 740, 80),
    ], [
      e('e1', 'V', 'out', 'ratio', 'in_0'),
      e('e2', 'Vref', 'out', 'ratio', 'in_1'),
      e('e3', 'ratio', 'out', 'log10v', 'in'),
      e('e4', 'twenty', 'out', 'dB', 'in_0'),
      e('e5', 'log10v', 'out', 'dB', 'in_1'),
      e('e6', 'dB', 'out', 'disp', 'in'),
    ]),
  },
]

// ── MATH ────────────────────────────────────────────────────────────────────

const MATH: ExampleGraph[] = [
  {
    id: 'math_quadratic',
    title: 'Quadratic Formula',
    domain: 'math',
    description: 'x = (-b ± √(b²-4ac)) / 2a. Roots of ax²+bx+c=0.',
    tags: ['quadratic', 'roots', 'polynomial', 'algebra'],
    difficulty: 'beginner',
    graph: g([
      n('a', 'number', { label: 'a', value: 1 }, 0, 0),
      n('b', 'number', { label: 'b', value: -5 }, 0, 80),
      n('c', 'number', { label: 'c', value: 6 }, 0, 160),
      n('b2', 'multiply', { label: 'b²' }, 200, 80),
      n('four', 'number', { label: '4', value: 4 }, 200, 160),
      n('four_ac', 'multiply', { label: '4ac' }, 380, 160),
      n('disc', 'subtract', { label: 'b²-4ac' }, 560, 120),
      n('sqrt_disc', 'sqrt', { label: '√discriminant' }, 730, 120),
      n('neg_b', 'negate', { label: '-b' }, 200, -40),
      n('two_a', 'multiply', { label: '2a' }, 200, -120),
      n('two', 'number', { label: '2', value: 2 }, 0, -120),
      n('x1_num', 'add', { label: '-b+√d' }, 900, 40),
      n('x2_num', 'subtract', { label: '-b-√d' }, 900, 160),
      n('x1', 'divide', { label: 'x₁' }, 1080, 40),
      n('x2', 'divide', { label: 'x₂' }, 1080, 160),
      n('disp1', 'display', { label: 'x₁' }, 1260, 40),
      n('disp2', 'display', { label: 'x₂' }, 1260, 160),
    ], [
      e('e1', 'b', 'out', 'b2', 'in_0'),
      e('e2', 'b', 'out', 'b2', 'in_1'),
      e('e3', 'four', 'out', 'four_ac', 'in_0'),
      e('e4', 'a', 'out', 'four_ac', 'in_1'),
      e('e5', 'four_ac', 'out', 'four_ac2', 'in_1'),
      e('e6', 'b2', 'out', 'disc', 'in_0'),
      e('e7', 'four_ac', 'out', 'disc', 'in_1'),
      e('e8', 'disc', 'out', 'sqrt_disc', 'in'),
      e('e9', 'b', 'out', 'neg_b', 'in'),
      e('e10', 'two', 'out', 'two_a', 'in_0'),
      e('e11', 'a', 'out', 'two_a', 'in_1'),
      e('e12', 'neg_b', 'out', 'x1_num', 'in_0'),
      e('e13', 'sqrt_disc', 'out', 'x1_num', 'in_1'),
      e('e14', 'neg_b', 'out', 'x2_num', 'in_0'),
      e('e15', 'sqrt_disc', 'out', 'x2_num', 'in_1'),
      e('e16', 'x1_num', 'out', 'x1', 'in_0'),
      e('e17', 'two_a', 'out', 'x1', 'in_1'),
      e('e18', 'x2_num', 'out', 'x2', 'in_0'),
      e('e19', 'two_a', 'out', 'x2', 'in_1'),
      e('e20', 'x1', 'out', 'disp1', 'in'),
      e('e21', 'x2', 'out', 'disp2', 'in'),
    ]),
  },
  {
    id: 'math_pythagorean',
    title: 'Pythagorean Theorem',
    domain: 'math',
    description: 'c = √(a²+b²). Hypotenuse of a right triangle.',
    tags: ['Pythagoras', 'triangle', 'geometry', 'distance'],
    difficulty: 'beginner',
    graph: g([
      n('a', 'number', { label: 'Side a', value: 3 }, 0, 0),
      n('b', 'number', { label: 'Side b', value: 4 }, 0, 80),
      n('a2', 'multiply', { label: 'a²' }, 200, 0),
      n('b2', 'multiply', { label: 'b²' }, 200, 80),
      n('sum', 'add', { label: 'a²+b²' }, 380, 40),
      n('c', 'sqrt', { label: 'c = √(a²+b²)' }, 560, 40),
      n('disp', 'display', { label: 'Hypotenuse c' }, 740, 40),
    ], [
      e('e1', 'a', 'out', 'a2', 'in_0'),
      e('e2', 'a', 'out', 'a2', 'in_1'),
      e('e3', 'b', 'out', 'b2', 'in_0'),
      e('e4', 'b', 'out', 'b2', 'in_1'),
      e('e5', 'a2', 'out', 'sum', 'in_0'),
      e('e6', 'b2', 'out', 'sum', 'in_1'),
      e('e7', 'sum', 'out', 'c', 'in'),
      e('e8', 'c', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'math_euler_identity',
    title: "Euler's Identity",
    domain: 'math',
    description: 'e^(iπ) + 1 = 0. The most beautiful equation in mathematics.',
    tags: ['Euler', 'complex', 'e', 'pi', 'identity'],
    difficulty: 'beginner',
    graph: g([
      n('pi', 'constant', { label: 'π', constantId: 'pi' }, 0, 0),
      n('e', 'constant', { label: 'e', constantId: 'e' }, 0, 80),
      n('e_pi', 'pow', { label: 'e^π' }, 200, 40),
      n('neg1', 'negate', { label: '-1' }, 200, 160),
      n('one', 'number', { label: '1', value: 1 }, 0, 160),
      n('sum', 'add', { label: 'e^π + (-1)' }, 380, 100),
      n('disp', 'display', { label: 'e^π - 1 ≈ 21.14' }, 560, 100),
    ], [
      e('e1', 'e', 'out', 'e_pi', 'in_0'),
      e('e2', 'pi', 'out', 'e_pi', 'in_1'),
      e('e3', 'one', 'out', 'neg1', 'in'),
      e('e4', 'e_pi', 'out', 'sum', 'in_0'),
      e('e5', 'neg1', 'out', 'sum', 'in_1'),
      e('e6', 'sum', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'math_compound_interest',
    title: 'Compound Interest',
    domain: 'math',
    description: 'A = P(1 + r/n)^(nt). Future value with compound interest.',
    tags: ['compound interest', 'finance', 'exponential growth'],
    difficulty: 'beginner',
    graph: g([
      n('P', 'number', { label: 'Principal P (£)', value: 1000 }, 0, 0),
      n('r', 'number', { label: 'Annual rate r', value: 0.05 }, 0, 80),
      n('n', 'number', { label: 'Compounds/year n', value: 12 }, 0, 160),
      n('t', 'number', { label: 'Time t (years)', value: 10 }, 0, 240),
      n('r_n', 'divide', { label: 'r/n' }, 200, 120),
      n('one', 'number', { label: '1', value: 1 }, 200, 40),
      n('base', 'add', { label: '1 + r/n' }, 380, 80),
      n('nt', 'multiply', { label: 'nt' }, 380, 200),
      n('pow', 'pow', { label: '(1+r/n)^nt' }, 560, 140),
      n('A', 'multiply', { label: 'A = P·(...)' }, 740, 80),
      n('disp', 'display', { label: 'Future value A (£)' }, 920, 80),
    ], [
      e('e1', 'r', 'out', 'r_n', 'in_0'),
      e('e2', 'n', 'out', 'r_n', 'in_1'),
      e('e3', 'one', 'out', 'base', 'in_0'),
      e('e4', 'r_n', 'out', 'base', 'in_1'),
      e('e5', 'n', 'out', 'nt', 'in_0'),
      e('e6', 't', 'out', 'nt', 'in_1'),
      e('e7', 'base', 'out', 'pow', 'in_0'),
      e('e8', 'nt', 'out', 'pow', 'in_1'),
      e('e9', 'P', 'out', 'A', 'in_0'),
      e('e10', 'pow', 'out', 'A', 'in_1'),
      e('e11', 'A', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'math_normal_distribution',
    title: 'Normal Distribution PDF',
    domain: 'math',
    description: 'f(x) = (1/σ√2π)·e^(-(x-μ)²/2σ²). Gaussian probability density.',
    tags: ['normal distribution', 'Gaussian', 'statistics', 'PDF'],
    difficulty: 'intermediate',
    graph: g([
      n('x', 'number', { label: 'x', value: 1.0 }, 0, 0),
      n('mu', 'number', { label: 'Mean μ', value: 0 }, 0, 80),
      n('sigma', 'number', { label: 'Std dev σ', value: 1 }, 0, 160),
      n('x_mu', 'subtract', { label: 'x-μ' }, 200, 40),
      n('num_sq', 'multiply', { label: '(x-μ)²' }, 380, 40),
      n('sig2', 'multiply', { label: 'σ²' }, 200, 160),
      n('two', 'number', { label: '2', value: 2 }, 0, 240),
      n('two_sig2', 'multiply', { label: '2σ²' }, 380, 200),
      n('frac', 'divide', { label: '(x-μ)²/2σ²' }, 560, 120),
      n('neg_frac', 'negate', { label: '-(x-μ)²/2σ²' }, 740, 120),
      n('exp_term', 'exp', { label: 'e^(-...)' }, 900, 120),
      n('two_pi', 'number', { label: '2π', value: 6.2831853 }, 200, 280),
      n('denom_sq', 'multiply', { label: '2πσ²' }, 380, 280),
      n('denom', 'sqrt', { label: '√(2πσ²)' }, 560, 280),
      n('f', 'divide', { label: 'f(x)' }, 1080, 200),
      n('disp', 'display', { label: 'f(x) Normal PDF' }, 1280, 200),
    ], [
      e('e1', 'x', 'out', 'x_mu', 'in_0'),
      e('e2', 'mu', 'out', 'x_mu', 'in_1'),
      e('e3', 'x_mu', 'out', 'num_sq', 'in_0'),
      e('e4', 'x_mu', 'out', 'num_sq', 'in_1'),
      e('e5', 'sigma', 'out', 'sig2', 'in_0'),
      e('e6', 'sigma', 'out', 'sig2', 'in_1'),
      e('e7', 'two', 'out', 'two_sig2', 'in_0'),
      e('e8', 'sig2', 'out', 'two_sig2', 'in_1'),
      e('e9', 'num_sq', 'out', 'frac', 'in_0'),
      e('e10', 'two_sig2', 'out', 'frac', 'in_1'),
      e('e11', 'frac', 'out', 'neg_frac', 'in'),
      e('e12', 'neg_frac', 'out', 'exp_term', 'in'),
      e('e13', 'two_pi', 'out', 'denom_sq', 'in_0'),
      e('e14', 'sig2', 'out', 'denom_sq', 'in_1'),
      e('e15', 'denom_sq', 'out', 'denom', 'in'),
      e('e16', 'exp_term', 'out', 'f', 'in_0'),
      e('e17', 'denom', 'out', 'f', 'in_1'),
      e('e18', 'f', 'out', 'disp', 'in'),
    ]),
  },
]

// ── FLUID ───────────────────────────────────────────────────────────────────

const FLUID: ExampleGraph[] = [
  {
    id: 'fluid_bernoulli',
    title: 'Bernoulli Equation',
    domain: 'fluid',
    description: 'P₁ + ½ρv₁² = P₂ + ½ρv₂². Pressure from velocity change.',
    tags: ['Bernoulli', 'pressure', 'flow', 'incompressible'],
    difficulty: 'intermediate',
    graph: g([
      n('P1', 'number', { label: 'P₁ (Pa)', value: 101325 }, 0, 0),
      n('rho', 'number', { label: 'Density ρ (kg/m³)', value: 1000 }, 0, 80),
      n('v1', 'number', { label: 'v₁ (m/s)', value: 2 }, 0, 160),
      n('v2', 'number', { label: 'v₂ (m/s)', value: 5 }, 0, 240),
      n('v1sq', 'multiply', { label: 'v₁²' }, 200, 160),
      n('v2sq', 'multiply', { label: 'v₂²' }, 200, 240),
      n('half', 'number', { label: '0.5', value: 0.5 }, 200, 320),
      n('dv', 'subtract', { label: 'v₁²-v₂²' }, 380, 200),
      n('dyn', 'multiply', { label: '½ρΔv²' }, 560, 240),
      n('rho_half', 'multiply', { label: '½ρ' }, 380, 300),
      n('P2', 'add', { label: 'P₂ = P₁+½ρ(v₁²-v₂²)' }, 740, 120),
      n('disp', 'display', { label: 'P₂ (Pa)' }, 920, 120),
    ], [
      e('e1', 'v1', 'out', 'v1sq', 'in_0'),
      e('e2', 'v1', 'out', 'v1sq', 'in_1'),
      e('e3', 'v2', 'out', 'v2sq', 'in_0'),
      e('e4', 'v2', 'out', 'v2sq', 'in_1'),
      e('e5', 'v1sq', 'out', 'dv', 'in_0'),
      e('e6', 'v2sq', 'out', 'dv', 'in_1'),
      e('e7', 'half', 'out', 'rho_half', 'in_0'),
      e('e8', 'rho', 'out', 'rho_half', 'in_1'),
      e('e9', 'rho_half', 'out', 'dyn', 'in_0'),
      e('e10', 'dv', 'out', 'dyn', 'in_1'),
      e('e11', 'P1', 'out', 'P2', 'in_0'),
      e('e12', 'dyn', 'out', 'P2', 'in_1'),
      e('e13', 'P2', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'fluid_reynolds',
    title: 'Reynolds Number',
    domain: 'fluid',
    description: 'Re = ρvL/μ. Laminar (Re<2300) vs turbulent (Re>4000).',
    tags: ['Reynolds number', 'turbulence', 'laminar', 'pipe flow'],
    difficulty: 'beginner',
    graph: g([
      n('rho', 'number', { label: 'Density ρ (kg/m³)', value: 1000 }, 0, 0),
      n('v', 'number', { label: 'Velocity v (m/s)', value: 1 }, 0, 80),
      n('L', 'number', { label: 'Length L (m)', value: 0.05 }, 0, 160),
      n('mu', 'number', { label: 'Viscosity μ (Pa·s)', value: 1e-3 }, 0, 240),
      n('rho_v', 'multiply', { label: 'ρv' }, 200, 40),
      n('rho_vL', 'multiply', { label: 'ρvL' }, 380, 100),
      n('Re', 'divide', { label: 'Re = ρvL/μ' }, 560, 160),
      n('disp', 'display', { label: 'Reynolds number' }, 740, 160),
    ], [
      e('e1', 'rho', 'out', 'rho_v', 'in_0'),
      e('e2', 'v', 'out', 'rho_v', 'in_1'),
      e('e3', 'rho_v', 'out', 'rho_vL', 'in_0'),
      e('e4', 'L', 'out', 'rho_vL', 'in_1'),
      e('e5', 'rho_vL', 'out', 'Re', 'in_0'),
      e('e6', 'mu', 'out', 'Re', 'in_1'),
      e('e7', 'Re', 'out', 'disp', 'in'),
    ]),
  },
]

// ── FINANCE ─────────────────────────────────────────────────────────────────

const FINANCE: ExampleGraph[] = [
  {
    id: 'fin_npv',
    title: 'Net Present Value',
    domain: 'finance',
    description: 'NPV = Σ Ct/(1+r)^t. Present value of cash flows.',
    tags: ['NPV', 'discounted cash flow', 'finance', 'investment'],
    difficulty: 'intermediate',
    graph: g([
      n('r', 'number', { label: 'Discount rate r', value: 0.1 }, 0, 0),
      n('C1', 'number', { label: 'CF year 1', value: 100 }, 0, 80),
      n('C2', 'number', { label: 'CF year 2', value: 150 }, 0, 160),
      n('C3', 'number', { label: 'CF year 3', value: 200 }, 0, 240),
      n('one', 'number', { label: '1', value: 1 }, 200, 0),
      n('one_r', 'add', { label: '1+r' }, 360, 0),
      n('df1', 'pow', { label: '(1+r)^1' }, 520, 0),
      n('df2', 'pow', { label: '(1+r)^2' }, 520, 80),
      n('df3', 'pow', { label: '(1+r)^3' }, 520, 160),
      n('exp1', 'number', { label: '1', value: 1 }, 360, 80),
      n('exp2', 'number', { label: '2', value: 2 }, 360, 160),
      n('exp3', 'number', { label: '3', value: 3 }, 360, 240),
      n('pv1', 'divide', { label: 'PV₁' }, 700, 0),
      n('pv2', 'divide', { label: 'PV₂' }, 700, 80),
      n('pv3', 'divide', { label: 'PV₃' }, 700, 160),
      n('npv', 'add', { label: 'NPV' }, 880, 80),
      n('disp', 'display', { label: 'NPV (£)' }, 1060, 80),
    ], [
      e('e1', 'one', 'out', 'one_r', 'in_0'),
      e('e2', 'r', 'out', 'one_r', 'in_1'),
      e('e3', 'one_r', 'out', 'df1', 'in_0'),
      e('e4', 'exp1', 'out', 'df1', 'in_1'),
      e('e5', 'one_r', 'out', 'df2', 'in_0'),
      e('e6', 'exp2', 'out', 'df2', 'in_1'),
      e('e7', 'one_r', 'out', 'df3', 'in_0'),
      e('e8', 'exp3', 'out', 'df3', 'in_1'),
      e('e9', 'C1', 'out', 'pv1', 'in_0'),
      e('e10', 'df1', 'out', 'pv1', 'in_1'),
      e('e11', 'C2', 'out', 'pv2', 'in_0'),
      e('e12', 'df2', 'out', 'pv2', 'in_1'),
      e('e13', 'C3', 'out', 'pv3', 'in_0'),
      e('e14', 'df3', 'out', 'pv3', 'in_1'),
      e('e15', 'pv1', 'out', 'npv', 'in_0'),
      e('e16', 'pv2', 'out', 'npv', 'in_1'),
      e('e17', 'pv3', 'out', 'npv', 'in_2'),
      e('e18', 'npv', 'out', 'disp', 'in'),
    ]),
  },
  {
    id: 'fin_black_scholes_d1',
    title: "Black-Scholes d₁",
    domain: 'finance',
    description: 'd₁ = (ln(S/K) + (r+σ²/2)T) / (σ√T). First BSM term.',
    tags: ['Black-Scholes', 'options', 'derivatives', 'finance'],
    difficulty: 'advanced',
    graph: g([
      n('S', 'number', { label: 'Stock price S', value: 100 }, 0, 0),
      n('K', 'number', { label: 'Strike K', value: 100 }, 0, 80),
      n('r', 'number', { label: 'Risk-free rate r', value: 0.05 }, 0, 160),
      n('sigma', 'number', { label: 'Volatility σ', value: 0.2 }, 0, 240),
      n('T', 'number', { label: 'Time to expiry T (yr)', value: 0.5 }, 0, 320),
      n('S_K', 'divide', { label: 'S/K' }, 200, 40),
      n('lnSK', 'ln', { label: 'ln(S/K)' }, 380, 40),
      n('sig2', 'multiply', { label: 'σ²' }, 200, 240),
      n('half', 'number', { label: '0.5', value: 0.5 }, 200, 320),
      n('sig2_2', 'multiply', { label: 'σ²/2' }, 380, 280),
      n('r_sig', 'add', { label: 'r+σ²/2' }, 560, 200),
      n('r_sig_T', 'multiply', { label: '(r+σ²/2)T' }, 740, 200),
      n('numer', 'add', { label: 'ln(S/K)+(r+σ²/2)T' }, 920, 120),
      n('sqrtT', 'sqrt', { label: '√T' }, 200, 400),
      n('sig_sqrtT', 'multiply', { label: 'σ√T' }, 380, 360),
      n('d1', 'divide', { label: 'd₁' }, 1100, 240),
      n('disp', 'display', { label: 'd₁ (BSM)' }, 1280, 240),
    ], [
      e('e1', 'S', 'out', 'S_K', 'in_0'),
      e('e2', 'K', 'out', 'S_K', 'in_1'),
      e('e3', 'S_K', 'out', 'lnSK', 'in'),
      e('e4', 'sigma', 'out', 'sig2', 'in_0'),
      e('e5', 'sigma', 'out', 'sig2', 'in_1'),
      e('e6', 'half', 'out', 'sig2_2', 'in_0'),
      e('e7', 'sig2', 'out', 'sig2_2', 'in_1'),
      e('e8', 'r', 'out', 'r_sig', 'in_0'),
      e('e9', 'sig2_2', 'out', 'r_sig', 'in_1'),
      e('e10', 'r_sig', 'out', 'r_sig_T', 'in_0'),
      e('e11', 'T', 'out', 'r_sig_T', 'in_1'),
      e('e12', 'lnSK', 'out', 'numer', 'in_0'),
      e('e13', 'r_sig_T', 'out', 'numer', 'in_1'),
      e('e14', 'T', 'out', 'sqrtT', 'in'),
      e('e15', 'sigma', 'out', 'sig_sqrtT', 'in_0'),
      e('e16', 'sqrtT', 'out', 'sig_sqrtT', 'in_1'),
      e('e17', 'numer', 'out', 'd1', 'in_0'),
      e('e18', 'sig_sqrtT', 'out', 'd1', 'in_1'),
      e('e19', 'd1', 'out', 'disp', 'in'),
    ]),
  },
]

// ── Combined catalog ──────────────────────────────────────────────────────────

export const EXAMPLE_GRAPHS: ExampleGraph[] = [
  ...MECHANICAL,
  ...ELECTRICAL,
  ...THERMAL,
  ...CONTROL,
  ...ML,
  ...OPTIMISATION,
  ...VEHICLE,
  ...SIGNAL,
  ...MATH,
  ...FLUID,
  ...FINANCE,
]

export const EXAMPLE_GRAPH_CATALOG: Record<ExampleDomain, ExampleGraph[]> = {
  mechanical: MECHANICAL,
  electrical: ELECTRICAL,
  thermal: THERMAL,
  fluid: FLUID,
  control: CONTROL,
  ml: ML,
  optimisation: OPTIMISATION,
  vehicle: VEHICLE,
  signal: SIGNAL,
  math: MATH,
  data: [],
  finance: FINANCE,
}

// ── Query helpers ──────────────────────────────────────────────────────────────

/** Return all examples for a given domain. */
export function getExamplesByDomain(domain: ExampleDomain): ExampleGraph[] {
  return EXAMPLE_GRAPH_CATALOG[domain] ?? []
}

/** Simple case-insensitive keyword search across title, description, and tags. */
export function searchExamples(query: string): ExampleGraph[] {
  if (!query.trim()) return EXAMPLE_GRAPHS
  const q = query.toLowerCase()
  return EXAMPLE_GRAPHS.filter(
    (ex) =>
      ex.title.toLowerCase().includes(q) ||
      ex.description.toLowerCase().includes(q) ||
      ex.tags.some((t) => t.toLowerCase().includes(q)) ||
      ex.domain.toLowerCase().includes(q),
  )
}

/** Return examples by difficulty. */
export function getExamplesByDifficulty(
  level: ExampleGraph['difficulty'],
): ExampleGraph[] {
  return EXAMPLE_GRAPHS.filter((ex) => ex.difficulty === level)
}
