/**
 * plot-spec.ts — Pure Vega-Lite spec generation.
 *
 * Input: a Value (vector, table) + PlotConfig.
 * Output: a Vega-Lite TopLevelSpec as a plain JSON object.
 *
 * No Vega/Vega-Lite imports here — this is a pure data transform.
 */

import type { Value } from '../engine/value'
import { isVector, isTable, isScalar, isError } from '../engine/value'
import type { PlotConfig, PlotThemePreset, ReferenceLine } from '../blocks/types'
import { lttbDownsample, type Point } from './downsample'

// ── Theme presets ──────────────────────────────────────────────────────────

export interface ThemeDimensions {
  width: number
  height: number
  fontSize: number
  titleFontSize: number
  padding: number
  background: string
  lineWidth: number
}

export const THEME_PRESETS: Record<PlotThemePreset, ThemeDimensions> = {
  'paper-single': {
    width: 360,
    height: 240,
    fontSize: 10,
    titleFontSize: 12,
    padding: 40,
    background: '#ffffff',
    lineWidth: 1.5,
  },
  'paper-double': {
    width: 720,
    height: 360,
    fontSize: 12,
    titleFontSize: 14,
    padding: 50,
    background: '#ffffff',
    lineWidth: 2,
  },
  presentation: {
    width: 960,
    height: 540,
    fontSize: 16,
    titleFontSize: 20,
    padding: 60,
    background: '#ffffff',
    lineWidth: 3,
  },
  report: {
    width: 680,
    height: 480,
    fontSize: 11,
    titleFontSize: 13,
    padding: 45,
    background: '#ffffff',
    lineWidth: 1.5,
  },
}

// ── Inline node preview dimensions ──────────────────────────────────────────

const INLINE_WIDTH = 280
const INLINE_HEIGHT = 180

// ── Data extraction ─────────────────────────────────────────────────────────

interface PlotData {
  values: Record<string, unknown>[]
  columns: string[]
  isDownsampled: boolean
  originalCount: number
}

function extractPlotData(value: Value, config: PlotConfig): PlotData | { error: string } {
  if (isError(value)) return { error: value.message }
  if (isScalar(value)) return { error: 'Plot needs a Vector or Table input' }

  if (isVector(value)) {
    const raw: Point[] = value.value.map((y, i) => ({ x: i, y }))
    const maxPts = config.maxPoints ?? 2000
    const downsampled = raw.length > maxPts
    const points = downsampled ? lttbDownsample(raw, maxPts) : raw
    return {
      values: points.map((p) => ({ x: p.x, y: p.y })),
      columns: ['x', 'y'],
      isDownsampled: downsampled,
      originalCount: raw.length,
    }
  }

  if (isTable(value)) {
    const cols = value.columns as string[]
    const values = (value.rows as readonly (readonly number[])[]).map((row) => {
      const obj: Record<string, unknown> = {}
      cols.forEach((c, i) => {
        obj[c] = row[i] ?? null
      })
      return obj
    })
    return {
      values,
      columns: cols,
      isDownsampled: false,
      originalCount: values.length,
    }
  }

  return { error: 'Unknown value type' }
}

// ── Spec builders ───────────────────────────────────────────────────────────

export interface SpecResult {
  spec: Record<string, unknown>
  isDownsampled: boolean
  originalCount: number
}

/**
 * Build a Vega-Lite spec for inline (node body) rendering.
 * Uses compact dimensions regardless of theme preset.
 * Pass interactive=true to enable scroll-to-zoom, drag-to-pan, and hover tooltips.
 */
export function buildInlineSpec(
  value: Value | undefined,
  config: PlotConfig,
  interactive = false,
): SpecResult | { error: string } {
  if (!value) return { error: 'No data connected' }
  return buildSpec(value, config, INLINE_WIDTH, INLINE_HEIGHT, interactive)
}

/**
 * Build a Vega-Lite spec for full-size (modal) rendering.
 * Uses theme preset dimensions.
 */
export function buildFullSpec(
  value: Value | undefined,
  config: PlotConfig,
): SpecResult | { error: string } {
  if (!value) return { error: 'No data connected' }
  const theme = THEME_PRESETS[config.themePreset ?? 'paper-single']
  const result = buildSpec(value, config, theme.width, theme.height)
  if ('error' in result) return result

  // Add branding text annotation when enabled
  if (config.showBranding) {
    addBrandingLayer(result.spec, theme.width, theme.height)
  }

  return result
}

/**
 * Adds a "Generated by ChainSolve" text annotation to the bottom-right
 * of the chart. Only used in full-size (export) specs, never inline preview.
 */
function addBrandingLayer(spec: Record<string, unknown>, width: number, height: number): void {
  const brandingMark = {
    mark: {
      type: 'text',
      align: 'right',
      baseline: 'bottom',
      fontSize: 9,
      font: "'Montserrat', system-ui, sans-serif",
      color: '#999999',
      x: width - 8,
      y: height - 4,
      text: 'Generated by ChainSolve',
    },
    data: { values: [{}] },
  }

  // If the spec already uses a layer (e.g. reference lines), append to it.
  // Otherwise, wrap mark+encoding into a layer structure.
  if (Array.isArray(spec.layer)) {
    ;(spec.layer as unknown[]).push(brandingMark)
  } else if (spec.mark && spec.encoding) {
    const mainLayer = { mark: spec.mark, encoding: spec.encoding }
    delete spec.mark
    delete spec.encoding
    if (spec.transform) {
      ;(mainLayer as Record<string, unknown>).transform = spec.transform
      delete spec.transform
    }
    spec.layer = [mainLayer, brandingMark]
  }
}

function buildSpec(
  value: Value,
  config: PlotConfig,
  width: number,
  height: number,
  interactive = false,
): SpecResult | { error: string } {
  const data = extractPlotData(value, config)
  if ('error' in data) return data

  const theme = THEME_PRESETS[config.themePreset ?? 'paper-single']

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const base: Record<string, any> = {
    $schema: 'https://vega.github.io/schema/vega-lite/v5.json',
    width,
    height,
    autosize: { type: 'fit', contains: 'padding' },
    background: theme.background,
    data: { values: data.values },
    config: {
      font: "'Montserrat', system-ui, sans-serif",
      axis: { labelFontSize: theme.fontSize, titleFontSize: theme.fontSize },
      title: { fontSize: theme.titleFontSize },
    },
  }

  if (config.title) {
    base.title = config.subtitle ? { text: config.title, subtitle: config.subtitle } : config.title
  }

  const xScale = config.xScale === 'log' ? { type: 'log' as const } : { type: 'linear' as const }
  const yScale = config.yScale === 'log' ? { type: 'log' as const } : { type: 'linear' as const }

  switch (config.chartType) {
    case 'xyLine':
    case 'xyScatter': {
      const xField = config.xColumn ?? data.columns[0] ?? 'x'
      const yFields = config.yColumns ?? [data.columns[1] ?? data.columns[0] ?? 'y']
      const markType = config.chartType === 'xyLine' ? 'line' : 'point'

      // Secondary Y-axis: when yColumns2 is configured, build a dual-axis layer spec
      const yFields2 = config.yColumns2 && config.yColumns2.length > 0 ? config.yColumns2 : null
      if (yFields2) {
        const y2Scale =
          config.y2Scale === 'log' ? { type: 'log' as const } : { type: 'linear' as const }

        // Primary layer (left axis)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const primaryLayer: Record<string, any> =
          yFields.length <= 1
            ? {
                mark: { type: markType, strokeWidth: theme.lineWidth, color: '#1CABB0' },
                encoding: {
                  x: {
                    field: xField,
                    type: 'quantitative',
                    scale: xScale,
                    title: config.xLabel,
                  },
                  y: {
                    field: yFields[0],
                    type: 'quantitative',
                    scale: yScale,
                    axis: { title: config.yLabel },
                  },
                },
              }
            : {
                transform: [{ fold: yFields, as: ['_series', '_val'] }],
                mark: { type: markType, strokeWidth: theme.lineWidth },
                encoding: {
                  x: {
                    field: xField,
                    type: 'quantitative',
                    scale: xScale,
                    title: config.xLabel,
                  },
                  y: {
                    field: '_val',
                    type: 'quantitative',
                    scale: yScale,
                    axis: { title: config.yLabel },
                  },
                  color: { field: '_series', type: 'nominal' },
                },
              }

        // Secondary layer (right axis, orange palette)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const secondaryLayer: Record<string, any> =
          yFields2.length <= 1
            ? {
                mark: {
                  type: markType,
                  strokeWidth: theme.lineWidth,
                  color: '#f97316',
                  strokeDash: [6, 3],
                },
                encoding: {
                  x: { field: xField, type: 'quantitative', scale: xScale },
                  y: {
                    field: yFields2[0],
                    type: 'quantitative',
                    scale: y2Scale,
                    axis: { orient: 'right', title: config.y2Label },
                  },
                },
              }
            : {
                transform: [{ fold: yFields2, as: ['_series2', '_val2'] }],
                mark: { type: markType, strokeWidth: theme.lineWidth, strokeDash: [6, 3] },
                encoding: {
                  x: { field: xField, type: 'quantitative', scale: xScale },
                  y: {
                    field: '_val2',
                    type: 'quantitative',
                    scale: y2Scale,
                    axis: { orient: 'right', title: config.y2Label },
                  },
                  color: { field: '_series2', type: 'nominal' },
                },
              }

        base.resolve = { scale: { y: 'independent' } }
        base.layer = [primaryLayer, secondaryLayer]
        break
      }

      // Single-axis (original behaviour)
      if (yFields.length <= 1) {
        base.mark = {
          type: markType,
          strokeWidth: theme.lineWidth,
        }
        base.encoding = {
          x: { field: xField, type: 'quantitative', scale: xScale, title: config.xLabel },
          y: {
            field: yFields[0],
            type: 'quantitative',
            scale: yScale,
            title: config.yLabel,
          },
        }
      } else {
        // Multi-series: fold yColumns
        base.transform = [{ fold: yFields, as: ['series', 'value'] }]
        base.mark = {
          type: markType,
          strokeWidth: theme.lineWidth,
        }
        base.encoding = {
          x: { field: xField, type: 'quantitative', scale: xScale, title: config.xLabel },
          y: { field: 'value', type: 'quantitative', scale: yScale, title: config.yLabel },
          color: { field: 'series', type: 'nominal' },
        }
      }
      break
    }

    case 'histogram': {
      const field = config.xColumn ?? data.columns[0] ?? 'y'
      base.mark = 'bar'
      base.encoding = {
        x: {
          field,
          type: 'quantitative',
          bin: { maxbins: config.binCount ?? 30 },
          title: config.xLabel,
        },
        y: { aggregate: 'count', title: config.yLabel ?? 'Count' },
      }
      break
    }

    case 'bar': {
      const xField = config.xColumn ?? data.columns[0] ?? 'x'
      const yField = config.yColumns?.[0] ?? data.columns[1] ?? data.columns[0] ?? 'y'
      base.mark = 'bar'
      base.encoding = {
        x: { field: xField, type: 'nominal', title: config.xLabel },
        y: { field: yField, type: 'quantitative', scale: yScale, title: config.yLabel },
      }
      break
    }

    case 'heatmap': {
      const xField = config.xColumn ?? data.columns[0] ?? 'x'
      const yField = config.yColumns?.[0] ?? data.columns[1] ?? 'y'
      const colorField = config.yColumns?.[1] ?? data.columns[2] ?? data.columns[1] ?? 'value'
      base.mark = 'rect'
      base.encoding = {
        x: { field: xField, type: 'ordinal', title: config.xLabel },
        y: { field: yField, type: 'ordinal', title: config.yLabel },
        color: { field: colorField, type: 'quantitative' },
      }
      break
    }

    case 'boxplot': {
      // Expects a table with optional grouping column (col 0) and value column (col 1),
      // or a vector (single distribution).
      if (data.columns.length >= 2) {
        const groupField = config.xColumn ?? data.columns[0] ?? 'group'
        const valueField = config.yColumns?.[0] ?? data.columns[1] ?? 'value'
        base.mark = { type: 'boxplot', extent: 1.5, median: { color: '#1CABB0' } }
        base.encoding = {
          x: { field: groupField, type: 'nominal', title: config.xLabel },
          y: { field: valueField, type: 'quantitative', scale: yScale, title: config.yLabel },
          color: { field: groupField, type: 'nominal', legend: config.showLegend ? {} : null },
        }
      } else {
        // Single vector: show as single box
        const valueField = data.columns[0] ?? 'y'
        base.mark = { type: 'boxplot', extent: 1.5, median: { color: '#1CABB0' } }
        base.encoding = {
          x: { value: width / 2 },
          y: { field: valueField, type: 'quantitative', scale: yScale, title: config.yLabel ?? 'Value' },
        }
      }
      break
    }

    case 'violin': {
      // Kernel density estimate rendered as an area mark.
      // Expects a table with optional grouping column and value column, or a single vector.
      if (data.columns.length >= 2) {
        const groupField = config.xColumn ?? data.columns[0] ?? 'group'
        const valueField = config.yColumns?.[0] ?? data.columns[1] ?? 'value'
        base.transform = [
          {
            density: valueField,
            groupby: [groupField],
            as: ['_val', '_density'],
          },
        ]
        base.mark = { type: 'area', orient: 'horizontal' }
        base.encoding = {
          x: {
            field: '_density',
            type: 'quantitative',
            stack: 'center',
            impute: null,
            title: null,
            axis: { labels: false, values: [0], grid: false, ticks: true },
          },
          y: { field: '_val', type: 'quantitative', scale: yScale, title: config.yLabel ?? 'Value' },
          color: { field: groupField, type: 'nominal', legend: config.showLegend ? {} : null },
          column: { field: groupField, header: { titleOrient: 'bottom' } },
        }
      } else {
        const valueField = data.columns[0] ?? 'y'
        base.transform = [{ density: valueField, as: ['_val', '_density'] }]
        base.mark = 'area'
        base.encoding = {
          x: { field: '_density', type: 'quantitative', title: 'Density' },
          y: { field: '_val', type: 'quantitative', scale: yScale, title: config.yLabel ?? 'Value' },
        }
      }
      break
    }

    case 'parallelCoords': {
      // Parallel coordinates: each column becomes an axis.
      // Expects a Table input with N numeric columns.
      // Uses Vega-Lite's fold transform + layer approach.
      const allCols = data.columns
      const colorField = config.xColumn // optional grouping/colour column
      const numericCols = colorField
        ? allCols.filter((c) => c !== colorField)
        : allCols

      if (numericCols.length === 0) {
        return { error: 'Parallel coordinates requires a Table input with numeric columns' }
      }

      base.transform = [
        {
          window: [{ op: 'count', as: '_index' }],
        },
        {
          fold: numericCols,
          as: ['_key', '_value'],
        },
        {
          joinaggregate: [
            { op: 'min', field: '_value', as: '_min' },
            { op: 'max', field: '_value', as: '_max' },
          ],
          groupby: ['_key'],
        },
        {
          calculate: 'datum._max === datum._min ? 0.5 : (datum._value - datum._min) / (datum._max - datum._min)',
          as: '_normValue',
        },
      ]
      base.layer = [
        {
          mark: { type: 'rule', color: '#ccc' },
          encoding: {
            detail: { aggregate: 'count' },
            x: { field: '_key', type: 'nominal' },
          },
        },
        {
          mark: 'line',
          encoding: {
            x: { field: '_key', type: 'nominal', axis: { title: null } },
            y: { field: '_normValue', type: 'quantitative', axis: { title: 'Normalised value', tickCount: 5 } },
            detail: { field: '_index', type: 'nominal' },
            color: colorField
              ? { field: colorField, type: 'nominal', legend: config.showLegend ? {} : null }
              : { value: '#1CABB0' },
            opacity: { value: 0.5 },
            tooltip: numericCols.map((c) => ({ field: c, type: 'quantitative' })),
          },
        },
      ]
      // Remove mark/encoding (we're using layers)
      delete base.mark
      delete base.encoding
      break
    }

    case 'contour': {
      // 2D density contour using Vega-Lite density2d transform.
      // Expects a Table with two numeric columns (x, y), or a vector (renders 1D distribution).
      if (data.columns.length >= 2) {
        const xField = config.xColumn ?? data.columns[0] ?? 'x'
        const yField = config.yColumns?.[0] ?? data.columns[1] ?? 'y'
        // Vega-Lite contour: use the 'density' transform + contour mark
        base.layer = [
          {
            mark: 'point',
            encoding: {
              x: { field: xField, type: 'quantitative', scale: xScale, title: config.xLabel },
              y: { field: yField, type: 'quantitative', scale: yScale, title: config.yLabel },
              opacity: { value: 0.3 },
              size: { value: 15 },
              color: { value: '#6b7280' },
            },
          },
          {
            transform: [
              {
                density: yField,
                groupby: [xField],
                extent: [null, null],
                as: ['_y', '_density'],
              },
            ],
            mark: 'line',
            encoding: {
              x: { field: xField, type: 'quantitative', scale: xScale },
              y: { field: '_y', type: 'quantitative', scale: yScale },
              color: { field: '_density', type: 'quantitative', scale: { scheme: 'viridis' } },
              detail: { field: xField, type: 'quantitative' },
            },
          },
        ]
        delete base.mark
        delete base.encoding
      } else {
        // 1D: density curve only
        const valueField = data.columns[0] ?? 'y'
        base.transform = [{ density: valueField, as: ['_val', '_density'] }]
        base.mark = { type: 'area', line: true, color: '#1CABB0', fillOpacity: 0.2 }
        base.encoding = {
          x: { field: '_val', type: 'quantitative', scale: xScale, title: config.xLabel ?? 'Value' },
          y: { field: '_density', type: 'quantitative', title: 'Density' },
        }
      }
      break
    }

    case 'bode': {
      // Bode plot: magnitude (dB) + phase (deg) vs frequency on log x-axis.
      // Expects a Table with columns: freq (Hz or rad/s), mag_dB, phase_deg.
      // If only 2 columns, treats col 0 as freq and col 1 as magnitude.
      const freqField = config.xColumn ?? data.columns[0] ?? 'freq'
      const magField = config.yColumns?.[0] ?? data.columns[1] ?? 'mag_dB'
      const phaseField = config.yColumns?.[1] ?? data.columns[2]

      const freqEnc = {
        field: freqField,
        type: 'quantitative' as const,
        scale: { type: 'log' as const },
        title: config.xLabel ?? 'Frequency',
        axis: { grid: config.showGrid ?? true },
      }

      if (phaseField) {
        // Two-panel Bode: magnitude top, phase bottom via vconcat
        base.vconcat = [
          {
            height: Math.round(height * 0.55),
            mark: { type: 'line', strokeWidth: theme.lineWidth, color: '#1CABB0' },
            encoding: {
              x: { ...freqEnc, axis: { ...freqEnc.axis, labels: false, title: null } },
              y: { field: magField, type: 'quantitative', title: config.yLabel ?? 'Magnitude (dB)', axis: { grid: config.showGrid ?? true } },
              tooltip: [
                { field: freqField, title: 'Freq', format: '.3g' },
                { field: magField, title: 'Mag (dB)', format: '.2f' },
              ],
            },
          },
          {
            height: Math.round(height * 0.35),
            mark: { type: 'line', strokeWidth: theme.lineWidth, color: '#f472b6' },
            encoding: {
              x: freqEnc,
              y: { field: phaseField, type: 'quantitative', title: 'Phase (deg)', axis: { grid: config.showGrid ?? true } },
              tooltip: [
                { field: freqField, title: 'Freq', format: '.3g' },
                { field: phaseField, title: 'Phase (°)', format: '.1f' },
              ],
            },
          },
        ]
        base.resolve = { scale: { x: 'shared' } }
        delete base.width
        delete base.height
      } else {
        // Single-panel: just magnitude
        base.mark = { type: 'line', strokeWidth: theme.lineWidth, color: '#1CABB0' }
        base.encoding = {
          x: freqEnc,
          y: { field: magField, type: 'quantitative', title: config.yLabel ?? 'Magnitude (dB)', axis: { grid: config.showGrid ?? true } },
          tooltip: [
            { field: freqField, title: 'Freq', format: '.3g' },
            { field: magField, title: 'Mag (dB)', format: '.2f' },
          ],
        }
      }
      break
    }

    case 'nyquist': {
      // Nyquist plot: Re(G(jω)) vs Im(G(jω)).
      // Expects a Table with columns: re, im (and optionally freq for tooltip).
      // Also draws the unit circle for reference and marks the -1+0j point.
      const reField = config.xColumn ?? data.columns[0] ?? 're'
      const imField = config.yColumns?.[0] ?? data.columns[1] ?? 'im'
      const freqTooltip = data.columns[2]
        ? [{ field: data.columns[2], title: 'Freq', format: '.3g' }]
        : []

      // Main locus + -1 point reference
      base.layer = [
        // Nyquist locus
        {
          mark: { type: 'line', strokeWidth: theme.lineWidth, color: '#1CABB0' },
          encoding: {
            x: { field: reField, type: 'quantitative', scale: xScale, title: config.xLabel ?? 'Re[G(jω)]', axis: { grid: config.showGrid ?? true } },
            y: { field: imField, type: 'quantitative', scale: yScale, title: config.yLabel ?? 'Im[G(jω)]', axis: { grid: config.showGrid ?? true } },
            tooltip: [
              { field: reField, title: 'Re', format: '.4f' },
              { field: imField, title: 'Im', format: '.4f' },
              ...freqTooltip,
            ],
          },
        },
        // Critical point marker at (-1, 0)
        {
          data: { values: [{ re: -1, im: 0 }] },
          mark: { type: 'point', shape: 'cross', size: 80, color: '#ef4444', strokeWidth: 2 },
          encoding: {
            x: { field: 're', type: 'quantitative' },
            y: { field: 'im', type: 'quantitative' },
          },
        },
        // Unit circle reference
        {
          data: {
            values: Array.from({ length: 361 }, (_, i) => ({
              re: Math.cos((i * Math.PI) / 180),
              im: Math.sin((i * Math.PI) / 180),
            })),
          },
          mark: { type: 'line', color: '#6b7280', strokeDash: [4, 4], strokeWidth: 0.8, opacity: 0.5 },
          encoding: {
            x: { field: 're', type: 'quantitative' },
            y: { field: 'im', type: 'quantitative' },
          },
        },
      ]
      delete base.mark
      delete base.encoding
      break
    }
  }

  // Grid
  if (base.encoding) {
    if (base.encoding.x) {
      base.encoding.x.axis = {
        ...(base.encoding.x.axis ?? {}),
        grid: config.showGrid ?? true,
      }
    }
    if (base.encoding.y && !base.encoding.y.aggregate) {
      base.encoding.y.axis = {
        ...(base.encoding.y.axis ?? {}),
        grid: config.showGrid ?? true,
      }
    }
  }

  // Legend
  if (!config.showLegend && base.encoding?.color) {
    base.encoding.color.legend = null
  }

  // Annotations (reference lines, bands, text labels) as extra Vega-Lite layers
  if (config.referenceLines && config.referenceLines.length > 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let existingLayers: Record<string, any>[]
    if (Array.isArray(base.layer)) {
      // Already layered (e.g. dual-axis, Nyquist, Bode): append annotation layers
      existingLayers = base.layer as Record<string, any>[]
    } else {
      // Not yet layered: wrap main spec into a layer
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mainLayer: Record<string, any> = { mark: base.mark, encoding: base.encoding }
      delete base.mark
      delete base.encoding
      if (base.transform) {
        mainLayer.transform = base.transform
        delete base.transform
      }
      existingLayers = [mainLayer]
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const annotationLayers: Record<string, any>[] = config.referenceLines.flatMap(
      (rl: ReferenceLine) => {
        const kind = rl.type ?? 'line'
        const colour = rl.color ?? '#ef4444'

        if (kind === 'band' && rl.axis && rl.value !== undefined && rl.value2 !== undefined) {
          // Shaded rectangular band between value and value2 on the given axis
          const isX = rl.axis === 'x'
          return [
            {
              mark: { type: 'rect', color: colour, opacity: 0.15 },
              encoding: isX
                ? { x: { datum: rl.value }, x2: { datum: rl.value2 } }
                : { y: { datum: rl.value }, y2: { datum: rl.value2 } },
            },
          ]
        }

        if (kind === 'text' && rl.x !== undefined && rl.y !== undefined) {
          // Floating text annotation at explicit (x, y) coordinates
          return [
            {
              mark: {
                type: 'text',
                color: colour,
                fontSize: 11,
                fontWeight: 600,
                align: 'left',
                baseline: 'bottom',
                dx: 4,
              },
              encoding: {
                x: { datum: rl.x },
                y: { datum: rl.y },
                text: { value: rl.text ?? '' },
              },
            },
          ]
        }

        // Default: reference line (rule mark) — original behaviour
        if (rl.axis && rl.value !== undefined) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const layers: Record<string, any>[] = [
            {
              mark: { type: 'rule', color: colour, strokeDash: [4, 4] },
              encoding: { [rl.axis]: { datum: rl.value } },
            },
          ]
          // Optional label on the line
          const labelText = rl.text ?? rl.label
          if (labelText) {
            layers.push({
              mark: {
                type: 'text',
                color: colour,
                fontSize: 10,
                align: rl.axis === 'x' ? 'left' : 'right',
                baseline: rl.axis === 'x' ? 'bottom' : 'middle',
                dx: rl.axis === 'x' ? 4 : -4,
                dy: rl.axis === 'x' ? -4 : 0,
              },
              encoding: {
                [rl.axis]: { datum: rl.value },
                text: { value: labelText },
              },
            })
          }
          return layers
        }

        return []
      },
    )

    base.layer = [...existingLayers, ...annotationLayers]
  }

  // Interactive: scroll-to-zoom, drag-to-pan (double-click resets), hover tooltip
  if (interactive) {
    base.params = [{ name: 'grid', select: 'interval', bind: 'scales' }]
    if (Array.isArray(base.layer)) {
      // Reference-lines case: tooltip goes on the main data layer
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mainLayer = base.layer[0] as Record<string, any>
      if (typeof mainLayer.mark === 'string') {
        mainLayer.mark = { type: mainLayer.mark, tooltip: true }
      } else if (mainLayer.mark && typeof mainLayer.mark === 'object') {
        mainLayer.mark = { ...mainLayer.mark, tooltip: true }
      }
    } else if (typeof base.mark === 'string') {
      base.mark = { type: base.mark, tooltip: true }
    } else if (base.mark && typeof base.mark === 'object') {
      base.mark = { ...base.mark, tooltip: true }
    }
  }

  return {
    spec: base,
    isDownsampled: data.isDownsampled,
    originalCount: data.originalCount,
  }
}
