/**
 * constantsCatalog.ts — Standalone constants catalog for the unified Constant picker (H4-1).
 *
 * All math, physics, atmospheric, thermodynamic, and electrical constants live here
 * with their exact values, labels, and descriptions. The unified Constant block reads
 * from this catalog; individual constant blocks are no longer registered.
 *
 * Legacy block types (pi, euler, tau, phi, const.*) still evaluate in the Rust engine
 * for backward compatibility with existing saved projects.
 */

export interface ConstantEntry {
  type: string
  label: string
  category: 'constants' | 'constMath' | 'constPhysics' | 'constAtmos' | 'constThermo' | 'constElec'
  value: number
  description: string
  /** PREC-03: Math symbol (e.g. "π", "e", "c"). */
  symbol?: string
  /** PREC-03: SI unit string (e.g. "m/s", "J·s", "C"). */
  unit?: string
  /** PREC-03: CODATA 2022 uncertainty string (e.g. "±1.9e-17"). Exact constants have "exact". */
  uncertainty?: string
  /** PREC-03: Source citation (default "CODATA 2022" for physics constants). */
  source?: string
}

// ── Catalog ─────────────────────────────────────────────────────────────────

export const CONSTANTS_CATALOG: ConstantEntry[] = [
  // ── Core math constants (legacy short types kept for backward compat) ───
  {
    type: 'pi',
    label: 'Pi',
    category: 'constants',
    value: Math.PI,
    description: 'Ratio of circumference to diameter',
    symbol: '\u03C0',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'euler',
    label: 'e (Euler)',
    category: 'constants',
    value: Math.E,
    description: 'Base of natural logarithms',
    symbol: 'e',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'tau',
    label: 'Tau',
    category: 'constants',
    value: 2 * Math.PI,
    description: 'Full turn in radians, 2\u03C0',
    symbol: '\u03C4',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'phi',
    label: 'Phi (Golden Ratio)',
    category: 'constants',
    value: 1.6180339887498948482,
    description: 'Golden ratio, (1+\u221A5)/2',
    symbol: '\u03C6',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },

  // ── Additional math constants (canonical const.math.* IDs — SCI-01) ────
  {
    type: 'const.math.pi',
    label: 'Pi',
    category: 'constMath',
    value: Math.PI,
    description: 'Ratio of circumference to diameter',
    symbol: '\u03C0',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.e',
    label: 'e (Euler)',
    category: 'constMath',
    value: Math.E,
    description: 'Base of natural logarithms',
    symbol: 'e',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.tau',
    label: 'Tau (2\u03C0)',
    category: 'constMath',
    value: 2 * Math.PI,
    description: 'Full turn in radians, 2\u03C0',
    symbol: '\u03C4',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.phi',
    label: 'Phi (Golden Ratio)',
    category: 'constMath',
    value: 1.6180339887498948482,
    description: 'Golden ratio, (1+\u221A5)/2',
    symbol: '\u03C6',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.sqrt2',
    label: 'sqrt(2)',
    category: 'constMath',
    value: Math.SQRT2,
    description: 'Square root of 2',
    symbol: '\u221A2',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.ln2',
    label: 'ln 2',
    category: 'constMath',
    value: Math.LN2,
    description: 'Natural logarithm of 2',
    symbol: 'ln 2',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },
  {
    type: 'const.math.ln10',
    label: 'ln 10',
    category: 'constMath',
    value: Math.LN10,
    description: 'Natural logarithm of 10',
    symbol: 'ln 10',
    uncertainty: 'exact (irrational)',
    source: 'Mathematics',
  },

  // ── Physics constants — CODATA 2022 (SCI-01) ───────────────────────────
  {
    type: 'const.physics.g0',
    label: 'g\u2080 (9.80665 m/s\u00B2)',
    category: 'constPhysics',
    value: 9.80665,
    description: 'Standard gravitational acceleration',
    symbol: 'g\u2080',
    unit: 'm/s\u00B2',
    uncertainty: 'exact',
    source: 'CGPM 1901',
  },
  {
    type: 'const.physics.R_molar',
    label: 'R (8.314 J/mol\u00B7K)',
    category: 'constPhysics',
    value: 8.314462618,
    description: 'Molar gas constant',
    symbol: 'R',
    unit: 'J\u00B7mol\u207B\u00B9\u00B7K\u207B\u00B9',
    uncertainty: 'exact',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.R',
    label: 'R (8.314 J/mol\u00B7K)',
    category: 'constPhysics',
    value: 8.314462618,
    description: 'Molar gas constant',
    symbol: 'R',
    unit: 'J\u00B7mol\u207B\u00B9\u00B7K\u207B\u00B9',
    uncertainty: 'exact',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.c',
    label: 'c (2.998\u00D710\u2078 m/s)',
    category: 'constPhysics',
    value: 299792458.0,
    description: 'Speed of light in vacuum',
    symbol: 'c',
    unit: 'm/s',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.h',
    label: 'h (Planck, 6.626\u00D710\u207B\u00B3\u2074 J\u00B7s)',
    category: 'constPhysics',
    value: 6.62607015e-34,
    description: 'Planck constant',
    symbol: 'h',
    unit: 'J\u00B7s',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.hbar',
    label: '\u210F (1.0546\u00D710\u207B\u00B3\u2074 J\u00B7s)',
    category: 'constPhysics',
    value: 1.0545718176461565e-34,
    description: 'Reduced Planck constant, h/(2\u03C0)',
    symbol: '\u210F',
    unit: 'J\u00B7s',
    uncertainty: 'exact',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.kB',
    label: 'k\u1D05 (Boltzmann, 1.381\u00D710\u207B\u00B2\u00B3 J/K)',
    category: 'constPhysics',
    value: 1.380649e-23,
    description: 'Boltzmann constant',
    symbol: 'k\u1D05',
    unit: 'J/K',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.Na',
    label: 'N\u2080 (Avogadro, 6.022\u00D710\u00B2\u00B3 mol\u207B\u00B9)',
    category: 'constPhysics',
    value: 6.02214076e23,
    description: "Avogadro's number",
    symbol: 'N\u2080',
    unit: 'mol\u207B\u00B9',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.NA',
    label: 'N\u2080 (Avogadro, 6.022\u00D710\u00B2\u00B3 mol\u207B\u00B9)',
    category: 'constPhysics',
    value: 6.02214076e23,
    description: "Avogadro's number",
    symbol: 'N\u2080',
    unit: 'mol\u207B\u00B9',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.qe',
    label: 'e (1.602\u00D710\u207B\u00B9\u2079 C)',
    category: 'constPhysics',
    value: 1.602176634e-19,
    description: 'Elementary charge',
    symbol: 'e',
    unit: 'C',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.e',
    label: 'e (1.602\u00D710\u207B\u00B9\u2079 C)',
    category: 'constPhysics',
    value: 1.602176634e-19,
    description: 'Elementary charge',
    symbol: 'e',
    unit: 'C',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.F',
    label: 'F (Faraday, 96 485 C/mol)',
    category: 'constPhysics',
    value: 96485.33212,
    description: 'Faraday constant, charge per mole of electrons',
    symbol: 'F',
    unit: 'C/mol',
    uncertainty: '\u00B10.000 30',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.me',
    label: 'm\u2091 (electron mass, 9.109\u00D710\u207B\u00B3\u00B9 kg)',
    category: 'constPhysics',
    value: 9.1093837139e-31,
    description: 'Electron rest mass',
    symbol: 'm\u2091',
    unit: 'kg',
    uncertainty: '\u00B10.000 000 0028e-31',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.mp',
    label: 'm\u209A (proton mass, 1.673\u00D710\u207B\u00B2\u2077 kg)',
    category: 'constPhysics',
    value: 1.67262192595e-27,
    description: 'Proton rest mass',
    symbol: 'm\u209A',
    unit: 'kg',
    uncertainty: '\u00B10.000 000 000 51e-27',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.mn',
    label: 'm\u2099 (neutron mass, 1.675\u00D710\u207B\u00B2\u2077 kg)',
    category: 'constPhysics',
    value: 1.67492750056e-27,
    description: 'Neutron rest mass',
    symbol: 'm\u2099',
    unit: 'kg',
    uncertainty: '\u00B10.000 000 000 85e-27',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.G',
    label: 'G (gravitational, 6.674\u00D710\u207B\u00B9\u00B9 m\u00B3/kg\u00B7s\u00B2)',
    category: 'constPhysics',
    value: 6.6743e-11,
    description: 'Newtonian gravitational constant',
    symbol: 'G',
    unit: 'm\u00B3/(kg\u00B7s\u00B2)',
    uncertainty: '\u00B10.000 15e-11',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.mu0',
    label: '\u03BC\u2080 (permeability, 1.257\u00D710\u207B\u2076 H/m)',
    category: 'constPhysics',
    value: 1.25663706127e-6,
    description: 'Vacuum magnetic permeability',
    symbol: '\u03BC\u2080',
    unit: 'H/m',
    uncertainty: '\u00B10.000 000 000 20e-6',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.eps0',
    label: '\u03B5\u2080 (permittivity, 8.854\u00D710\u207B\u00B9\u00B2 F/m)',
    category: 'constPhysics',
    value: 8.8541878188e-12,
    description: 'Vacuum electric permittivity',
    symbol: '\u03B5\u2080',
    unit: 'F/m',
    uncertainty: '\u00B10.000 000 0013e-12',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.sigma_sb',
    label: '\u03C3 (Stefan-Boltzmann, 5.671\u00D710\u207B\u2078 W/m\u00B2\u00B7K\u2074)',
    category: 'constPhysics',
    value: 5.670374419e-8,
    description: 'Stefan-Boltzmann constant',
    symbol: '\u03C3',
    unit: 'W/(m\u00B2\u00B7K\u2074)',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.sigma',
    label: '\u03C3 (Stefan-Boltzmann, 5.671\u00D710\u207B\u2078 W/m\u00B2\u00B7K\u2074)',
    category: 'constPhysics',
    value: 5.670374419e-8,
    description: 'Stefan-Boltzmann constant',
    symbol: '\u03C3',
    unit: 'W/(m\u00B2\u00B7K\u2074)',
    uncertainty: 'exact',
    source: 'SI 2019',
  },
  {
    type: 'const.physics.alpha',
    label: '\u03B1 (fine-structure, 7.297\u00D710\u207B\u00B3)',
    category: 'constPhysics',
    value: 7.2973525643e-3,
    description: 'Fine-structure constant',
    symbol: '\u03B1',
    unit: '(dimensionless)',
    uncertainty: '\u00B10.000 000 000 11e-3',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.Ry',
    label: 'R\u221E (Rydberg, 1.097\u00D710\u2077 m\u207B\u00B9)',
    category: 'constPhysics',
    value: 10973731.568157,
    description: 'Rydberg constant',
    symbol: 'R\u221E',
    unit: 'm\u207B\u00B9',
    uncertainty: '\u00B10.000 012',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.amu',
    label: 'u (atomic mass unit, 1.661\u00D710\u207B\u00B2\u2077 kg)',
    category: 'constPhysics',
    value: 1.66053906892e-27,
    description: 'Unified atomic mass unit (dalton)',
    symbol: 'u',
    unit: 'kg',
    uncertainty: '\u00B10.000 000 000 52e-27',
    source: 'CODATA 2022',
  },
  {
    type: 'const.physics.u',
    label: 'u (atomic mass unit, 1.661\u00D710\u207B\u00B2\u2077 kg)',
    category: 'constPhysics',
    value: 1.66053906892e-27,
    description: 'Unified atomic mass unit (dalton)',
    symbol: 'u',
    unit: 'kg',
    uncertainty: '\u00B10.000 000 000 52e-27',
    source: 'CODATA 2022',
  },

  // ── Atmospheric constants ───────────────────────────────────────────────
  {
    type: 'const.atmos.p0_pa',
    label: 'p0 (101 325 Pa)',
    category: 'constAtmos',
    value: 101_325.0,
    description: 'Standard atmospheric pressure at sea level',
  },
  {
    type: 'const.atmos.t0_k',
    label: 'T0 (288.15 K)',
    category: 'constAtmos',
    value: 288.15,
    description: 'ISA sea-level temperature',
  },
  {
    type: 'const.atmos.rho_air_sl',
    label: 'rho_air (1.225 kg/m3)',
    category: 'constAtmos',
    value: 1.225,
    description: 'Air density at sea level, standard conditions',
  },
  {
    type: 'const.atmos.gamma_air',
    label: 'gamma_air (1.4)',
    category: 'constAtmos',
    value: 1.4,
    description: 'Ratio of specific heats for air',
  },
  {
    type: 'const.atmos.R_air',
    label: 'R_air (287.05 J/kg K)',
    category: 'constAtmos',
    value: 287.05,
    description: 'Specific gas constant for dry air',
  },
  {
    type: 'const.atmos.mu_air_20c',
    label: 'mu_air (1.81e-5 Pa s)',
    category: 'constAtmos',
    value: 1.81e-5,
    description: 'Dynamic viscosity of air at 20 C',
  },
  {
    type: 'const.atmos.a_air_20c',
    label: 'a_air (343 m/s)',
    category: 'constAtmos',
    value: 343.0,
    description: 'Speed of sound in air at 20 C',
  },

  // ── Thermodynamic constants ─────────────────────────────────────────────
  {
    type: 'const.thermo.cp_air',
    label: 'cp_air (1005 J/kg K)',
    category: 'constThermo',
    value: 1005.0,
    description: 'Specific heat of air at constant pressure',
  },
  {
    type: 'const.thermo.cv_air',
    label: 'cv_air (718 J/kg K)',
    category: 'constThermo',
    value: 718.0,
    description: 'Specific heat of air at constant volume',
  },
  {
    type: 'const.thermo.k_air',
    label: 'k_air (0.026 W/m K)',
    category: 'constThermo',
    value: 0.0262,
    description: 'Thermal conductivity of air at 20 C',
  },
  {
    type: 'const.thermo.k_water',
    label: 'k_water (0.606 W/m K)',
    category: 'constThermo',
    value: 0.6,
    description: 'Thermal conductivity of water at 25 C',
  },

  // ── Electrical constants ────────────────────────────────────────────────
  {
    type: 'const.elec.rho_copper',
    label: 'rho_Cu (1.68e-8 ohm m)',
    category: 'constElec',
    value: 1.68e-8,
    description: 'Electrical resistivity of copper at 20 C',
  },
  {
    type: 'const.elec.rho_aluminium',
    label: 'rho_Al (2.82e-8 ohm m)',
    category: 'constElec',
    value: 2.82e-8,
    description: 'Electrical resistivity of aluminium at 20 C',
  },
]

// ── Lookup map: type → value ─────────────────────────────────────────────────

export const CONSTANT_VALUES: Record<string, number> = Object.fromEntries(
  CONSTANTS_CATALOG.map((c) => [c.type, c.value]),
)
